### ISSUE TITLE
Segment Truncation

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1215]
**Problem description**
We need to support compaction and more fine grained retention policies. As part of this, we should support truncation of all data before a supplied offset on a per segment basis. See #284 for more details.

**Problem location**
StreamSegmentStore

**Suggestions for an improvement**
Provide an API in `StreamSegmentStore` along the lines of:
`CompletableFuture<Void> truncateStreamSegment(String streamSegmentName, long offset);`

Details:
- This cannot be applied to transactions.
- Upon completion, this will set an internal attribute (or some other bit) on the Segment which indicates the lowest available offset for reading.
- For correctness, a Segment can only be truncated progressively (i.e., once we truncate at offset A, we can only truncate at offset B>=A).
- Once a Segment is truncated in its entirety (truncation offset >= Segment length), it should be deleted.
- Reads below the truncation offset are not allowed.
    - In-progress reads for a Segment during truncation will be canceled if their current ReadOffset is below the Truncation offset. 
    - Otherwise, the reads will proceed normally.
    - Since technically every offset in the segment is still accessible (in Tier2), it should be sufficient to do the offset check in the `StreamSegmentReadIndex` class.
- In order to maintain our consistency guarantees, we should not do any offset adjustment. Once set, the value at a particular offset should never change. As such, upon truncation, the truncation offset will not become offset 0 in the segment. Instead, the `GetSegmentInfo` method will return an additional field that contains the first offset available for reading. Any access below this offset will not be allowed.

**Comment by fpj** [comment]
@andreipaduroiu I have a few questions about the proposal in the description:

1. In the 5th bullet, we say:
```
Since technically every offset in the segment is still accessible (in Tier2)
```

Just so that I make sure I understand what this is saying, does it mean that we aren't truncating the data in Tier 2?

2. About this observation:
```
it should be sufficient to do the offset check in the StreamSegmentReadIndex#getMultiReadResultEntry
```

Could you remind me whether we evict data about a segment from the read index? Or is it the case the  read index always contains metadata about all existing segments in the container?

3.  About this observation:
```
For simplicity, once a segment is truncated, its truncation point becomes new offset 0.
```

What if clients of the segment store are storing offsets for a given segment and we change the offset value for the same data due to a truncation? It could lead to incorrect results, no? It might be better not to do it to avoid such a confusion with the offsets, but I'm wondering whether this is strictly necessary.

**Comment by andreipaduroiu** [comment]
1. We can't really truncate data in Tier2. Not all Tier2 implementations support native truncations. For those, we will need to create a new segment and copy the rest of the data to it. For a large segment with many successive truncations, this will be A LOT of data being copied around many times via the SegmentStore client. On top of that, we will need to either cancel/suspend current reads and block new reads while the truncation happens. The Tier2 truncation and metadata/readindex updates cannot be done atomically so it's very likely a Tier2 read request issued just prior to truncation will read the wrong data without even knowing it.
2. The ReadIndex will work as usual. Unused data will be evicted eventually. Since data that is truncated out will not be accessible anymore, the regular Cache eviction process will take care of this without any further changes needed.
3. We need to agree what to do here. Do we still keep the physical offsets around and throw when someone wants to access a truncated offset? Or we do as indicated in the description (truncated offset becomes offset 0, since that's where the segment really begins now).
