### ISSUE TITLE
API Compatibility (Producer and Consumer APIs)

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#13]
A vast majority of organizations with Data Pipelines in production today use Kafka as their primary messaging cluster. To enable them easily to migrate to Pravega, it is essential to give them a Kafka compatible API on top of Streaming Storage so that they don't have to recode the production producers/consumers. 

Pravega should be 100% compatible with Kafka 0.10.X API for clients (Producers/Consumers - Data plane)
Drop in replacement for existing Kafka clusters.
Reuse developer familiarity with Kafka APIs.
Leverage existing tools like Kafka Connect, Schema Registry, Mirror Maker

---

Some APIs might not be supportable (like getMetrics()). Those should be documented.

**Comment by schrepfler** [comment]
It's not quite clear if the feature was delivered under 0.3.0?

**Comment by shafqatevo** [comment]
I think this is a very important issue. A design goal should be to enable use of Kafka Streams library transparently with Pravega as a drop-in replacement for Kafka.

Was there any progress for this issue?

**Comment by tkaitchuck** [comment]
@shafqatevo Reopening.
There has not been any code progress. We decided to defer implementation, in favor of improvements to the rest of the system. We did evaluate it, and I am not sure 100% compatibility is achievable or a reasonable goal. In particular there are many things around metrics and config values that don't really make sense. However getting it so that the basic sending and receiving of events works as expected seems fairly achievable.

**Comment by shafqatevo** [comment]
Thanks @tkaitchuck !

Yes 100% compatibility may not be required. It will be a huge gain for users if Kafka Streams library can be used with Pravega instead of Kafka - more or less transparently - on top of the Pravega adapter for Kafka. Current work around will be to use a Kafka connector for Pravega, which also doesn't exist now.

**Comment by fpj** [comment]
Refer to https://github.com/pravega/kafka-adapter.
