### ISSUE TITLE
Key features documentation re Data in one place

### ISSUE THREAD

**Issue by Johnlon** [pravega/pravega#1319]
**Problem description**
The key features page claims that unlike other solutions pravega keeps the data in one place, using search/lucene as an example of where data gets stored multiple times.
However the key features page does not explain how it facilitates eg search without creating extra copies of the data in some manner.

**Problem location**
Key features page

**Suggestions for an improvement**
Given that the page mentions certain tech, such as Search/lucene, causing extra copies of the data, the page should document how pravega provides similar facilities without creating copies.

**Comment by sriksatya** [comment]
Data is created in Pravega as streams and automatically tiered to Tier-2 storage. A search engine can be built with raw data in Pravega, instead of copying the data to a separate search engine. This is one of the reason to open source Pravega. Middleware products such as Search engine can be built with reference to data in Pravega. It is not built yet. Pravega has the features necessary to make this happen.

**Comment by Johnlon** [comment]
Might want to make that clearer in the documentation
