### ISSUE TITLE
Disaster recovery

### ISSUE THREAD

**Issue by Johnlon** [pravega/pravega#1320]
**Problem description**
No documentation provided of setting up a multi DC deployment that is resilient to a DC loss.

**Problem location**
Documentation

**Suggestions for an improvement**
Provide tried and tested recommended DR scheme for the product. 
Document the strength and weaknesses.

**Comment by sriksatya** [comment]
Currently DR is through tier-2 storage only. Depending on what you use as Tier-2 storage an appropriate DR story applies.

**Comment by Johnlon** [comment]
What about the data in Bookkeeper that's not yet on t2 storage?

**Comment by Johnlon** [comment]
Again please document this. Thanks

**Comment by fpj** [comment]
Before documenting, we actually need to determine what the best approach is here. Synchronous writes to a bookie in a different data center will affect performance. While some applications might be ok with the performance penalty, some others might prefer to disable such synchronous writes at the cost of losing data in Tier 1 (bk) upon a data center going down. My suggestion is that we add cross-dc synchronous bk writes as an option.

Currently, we don't have such an option and as @sriksatya mentioned, we rely on Tier 2 to replicate it asynchronously, which clearly doesn't guarantee no data loss in the case of a data center going down.

We have an item in our roadmap for this (http://pravega.io/docs/roadmap/), but it is currently unversioned. We might want to promote and include it in one of the planned releases so that we work on it sooner depending on interest. I feel that @Johnlon opening this issue is definitely an indication of interest.

**Comment by Johnlon** [comment]
Definitely.

Proper top to bottom, availability planning, documentation and testing is one of the things that distinguishes interesting toys front enterprise software.

Also it works be interesting to see how this stacks up against jepsen testing. Any work done on that

**Comment by fpj** [comment]
We have not done any jepsen or other kind of fault injection testing, and frankly, we are not at the point of doing it yet. I don't know if it stands out for you in the documentation, but we are still fairly early on in the development of Pravega and it is not production-grade at the moment. We are working towards this goal and it is definitely in the plan to increase test coverage over time. We have talked about fault injection, but we haven't really scheduled the work yet.
