### ISSUE TITLE
Client should shade its dependencies

### ISSUE THREAD

**Issue by Prabha-Veerubhotla** [pravega/pravega#1339]
**Problem description**
The shading work that is presently done in the connector should be moved to the client library.
The connector currently  relocates all the dependencies and removes the client library from its effective POM.
But, this is not an ideal way, it's the responsibility of client to take care of shading it's dependencies.

Related to #1142 
**Problem location**
build.gradle ,project(client)

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
Closing in favor of #1887 which is a more limited from of this.

**Comment by tkaitchuck** [comment]
As mentioned above the current plan is to reduce the number of dependencies. (We have an issue tracking this for the whole of pravega. https://github.com/pravega/pravega/issues/1035 ) And implement #1887, but not actually shade the dependencies that are needed for the target the application needs.

**Comment by sachin-j-joshi** [comment]
@EronWright Below I am summarizing my discussions with you and the team.

The client jar artifact can be packaged in 3 ways
_A.	Lean_ -  unbundled, not relocated
_B.	Fat_ - all dependencies bundled ,  but not relocated
_C.	Shaded_ -  all dependencies bundled and relocated
 
 
In addition - We can think  of users for pravega client in two broad categories. 
_1.	Internal code_ (Eg. Tests, utilities and any server components)
_2.	External clients_ ( Eg. connectors, direct end user code)
 
The pravega client itself does not directly depend on the problematic libraries like netty or guava, but depends on them indirectly/trasitively via 'shared:protocol' project jar. 
 
Shading netty or guava in protocol jar itself is a non starter because it requires actual code changes in lots of places (as a result of relocating some of the types used in wire protocol to a different package) . Ideally a solution should be purely at packaging level and definitely should not cause any code changes.
 
Instead, a more practical and straightforward solution is to produce both shaded and unshaded versions of pravega-client.  In short we provide lean and shaded artifact (A and C above)
 
1.	The internal code - (Tests, utilities and any server components) should continue to depend on unshaded version and should explicitly provide any transitive dependencies (and deal with version conflicts appropriately). This is what we are doing today and as such no new change is required, as far as this category is concerned.
2.	External code - should depend on shaded artifact 'pravega-client-all'. The transitive dependencies are embeded and relocated in the pravega-client-all.jar 
 
**Open question -** 
Do we have to publish both Lean and Shaded jar to maven ?  Will it be sufficient to publish just the lean jar (A) in maven and provide shaded jar (C) as a build target (and a download) ? If not why not?
 
**Pros** 
- We are giving end users a  choice to select between using either shaded or unshaded jar
- Nothing changes as far as the internal usage is concerned, we'll continue using unshaded jar.
- Avoids over engineering. We don't have to start with a perfect guess about what all clients need. (giving us opportunity to react as users ask for a different behaviour)

**Cons**

- Once we shade a jar the whole dependency tree is fossilized in relocated bytecode. End user can not patch the security fixes in third party libs. They will have to wait for our release. Backporting such fixes requires yet another separate backlog workstreams of release management and tracking (may be not a big deal but still)
- We'll have multiple maven artifacts to maintain
- An implicit assumption here is that once we shade client, the connector  etc will not be required to shade their dependencies. If this is NOT going to be case then we are back to square one and not actually solving the original problem. Today we are shading dependencies in flink-connector anyway, so if nothing changes there changes after fixing this issue then not sure what real value it adds.

**Comment by tkaitchuck** [comment]
I'm going to attempt to clarify:
The dependencies of applications depending on the client library.
1.	With Maven. (gradle/ant)
1.	Manually.

In general every system that we anticipate running an automated build process will probably be using a dependency manager. However manually downloading dependencies can be useful for:
* Getting and writing a test application quickly
* Running a stand alone test
Etc. 

As such combining all the code into a single Jar/tarball makes sense for a release artifact for humans to download but not for maven.

There is a separate an independent consideration: Shading dependencies. 
For applications that depend on multiple libraries it is possible they will both depend on the same library. If they depend on incomparable versions of the package that occupy the same namespace, the code will never be able to execute. (This has the advantage of being caught quickly, but can be frustrating to resolve if you don't own either of the offending packages)

There are different approaches to managing this problem:
* OSGi
* Use Java 11
* Manually specify versions in Maven
* Shade each dependency

Different apps are going to take different approaches. For the Pravega server we are taking the manually specifying versions approach. For the Flink Connector I understand it is shading each of it's dependencies. 

The overlap between the dependency conflict resolution solution and the thin/fat artifact question came in the form of the stand alone client. There a test application needs to link against an artifact that could conflict with other things. This is different from the normal problem that could arise with the simple client because the full Controller/Server stack contains many more dependencies than the normal client that applications (especially those manually specifying versions) want to deal with.

The solution we went with was to have the stand alone server build target shade the dependencies so that a test application could link against it without having to jump through any additional hoops. 

The danger of this is that we become responsible for distributing updates. IE: Every time there is a bugfix, or security fix, patch release of any of our transitive dependencies we have to cut a new version. 
The thinking was that for the standalone Pravega instance this was OK, and we simply wouldn't do any of this work, because nobody would care. It was only every intended to be used for tests.

**Comment by EronWright** [comment]
@sachin-j-joshi the plan seems good.  I strongly believe that external clients should use the shaded jar, and I don't see a use-case for the lean jar for external clients.  Keep in mind that the problem we're trying to solve is a dependency conflict between Pravega client and the application environment.

(now going to read Tom's reply)

**Comment by tkaitchuck** [comment]
As a result I think we should still aim for the application being able to control which versions of dependencies are used. I don't see any usecase where an application would want a maven published fat jar containing dependencies they can't update and one that we won't. This leaves them open to unfixable security vulnerabilities indefinably. 

The solution then is to have a gradle target that can bundle dependencies and shade Jars. We will defiantly use this for the Standalone. We can also extend this to have a all in one client artifact, which might be useful for putting on our release page to help people get-started. However in Maven we would continue to explicitly declare all dependencies and allow maven to be used to manage them normally.

**Comment by EronWright** [comment]
I agree that we may assume the use of Maven-like dependency resolution in all build environments, which is why the 'fat' jar (2) is not interesting. 

You guys are getting hung up on security fixes but the practice of internalizing dependencies has become utterly commonplace.  It is motivated by the problem of dependency conflicts which has become acute.

@sachin-j-joshi the mission is clear: publish the fat jar as you described.  Then we may simplify the flink connector, the hadoop connector, etc.

**Comment by tkaitchuck** [comment]
@EronWright I don't understand your rely. I don't know how to reconcile:
> I agree that we may assume the use of Maven-like dependency resolution in all build environments, which is why the 'fat' jar (2) is not interesting.

with 
> publish the fat jar as you described. Then we may simplify the flink connector, the hadoop connector, etc.

Are you in favor of the fat jar or not? Or are the last two sentences unrelated?

**Comment by EronWright** [comment]
Oops I mean 'publish the shaded jar', thanks.

**Comment by fpj** [comment]
I'm not convinced that it is a good idea to have only the fat jar. That would force us to release a new version every time there is an update to a dependency, in particular, if there is a critical fix like a fix to a critical bug or vulnerability issue. Even if we have the fat shaded jar for convenience, it is not clear that we wouldn't have to maintain it frequently because users will request it.

From the comments, it is not that others are hung up on the idea, it is more like it is going to increase the maintenance work without a clear payoff. I have seen this kind of ask in other projects, so I'm not surprised to see it coming. I'm in general on the fence about doing this, and I'm less inclined to support  the ask at this point because we can do the necessary work in the connectors ourselves. 

I'm also wondering what would need to happen to the controller artifact as the controller uses the client for internal streams. Are there any changes required to the controller code in this case, like with imports and such? 

Overall, I see that it is convenient for the user to have a fat jar, shaded or not.  The main drawback I see with maintaining fat jars is keeping up with the releases of dependencies.

**Comment by eolivelli** [comment]
I'm not convinced that it is a good idea to have only the fat jar

+1 better to have the uber jar and the most skinny

**Comment by EronWright** [comment]
@fpj you'd best use the terminology in @sachin-j-joshi's post, lest @tkaitchuck become confused. :)

Feel free to publish both the lean jar (A) and the shaded jar (C).

**Comment by tkaitchuck** [comment]
@EronWright So obviously there were a lot of conflicts with the standalone jar. But what about the client itself. What dependencies have there been issues with? Guava?

**Comment by tkaitchuck** [comment]
In this discussion, I think the more important clarification is to define 'publish'. I assume this means publish to maven, as opposed to putting it here: https://github.com/pravega/pravega/releases

**Comment by EronWright** [comment]
I would think maven, thanks.

**Comment by tkaitchuck** [comment]
I don't think we have consensus on which of the approaches we should take. (Except for with standalone which is in progress here https://github.com/pravega/pravega/pull/3196 )

**Comment by EronWright** [comment]
@fpj @tkaitchuck please be prepared for a detailed conversation about this, next week.
