### ISSUE TITLE
Transaction segments as top level segments

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1344]
Today transaction segments are treated differently from other segments. This allows them to be routed to the same container as their parent segment, and merged. It also allows us to make simplifications like deleting a parent segment will delete all associated transaction segments.

However if we were to remove these special cases we could solve some problems more elegantly. For example https://github.com/pravega/flink-connectors/issues/5 .

The restrictions we need to maintain are:
* Only a sealed segment may be merged.
* A segment can only be merged into a segment that exists and is not sealed.
* A TXN segment must be routed to the same container as its parent.

Today we solve the last last issue by having the name of the transaction segment by <segmentName>#<TxnId> and detect the '#' and use it to route by the parent segment name. We could be more explicit and specify the container to route to directly. If we did this the server would not know what parent segment the segment was associated with until merge was invoked. 

The advantage of this sort of scheme, is while it is usually more efficient to simply merge transactions, it presents problems with scaling. With this scheme we could still merge transactions from before a scaling event afterwards event without #179 . 

We could treat the transaction commit as a metadata operation in the controller. It would seal the transaction segments and the stream segments, add the transaction segments to the end of the metadata as though whatever scaling operation had been performed in the interim was undone, and then add new segments for the writer as though the scaling operation were re-done. So from the Store's perspective no merge occurs. Example:
If a Stream has segment 1 and an transaction T, then if it scaled up to have two segments [2, 3] then T were to commit the history would look like [1], [2,3], [T1], [4,5]. This mechanism would also make it easier to implement transactions that contain data for multiple streams.

**Comment by fpj** [comment]
This is a valid and good direction. I like very much the direction of making the merge of txn segments more flexible, but I still dislike the limitation that the third constraint in the list above imposes. Merging a txn is pretty much a concatenation operation in tier 2. Limiting the txn segment to be in the same container is somewhat artificial and if we could simply look at a txn segment as a file shared via tier 2 that we need to merge to a parent segment no matter what container it belongs to, then we should be able to to have txns perpetually rolling. We would also be able to get rid of that pesky scale grace period.

Although the direction of this issue is towards making the merge of txns more flexible, which can help with the link connector issue mentioned, I'm not sure how we would expose it via the API. Perhaps the exact API changes aren't part of the issue, which is fine, but we need to at least have some idea so that we know we are solving the problem.

**Comment by andreipaduroiu** [comment]
> Merging a txn is pretty much a concatenation operation in tier 2

This is a gross oversimplification. Step 1 of the merge happens in the SSS metadata and read index. The concat to tier 2 happens much later (seconds, maybe minutes). During this time the data in the txn must be readily available for reading in the parent segment. This is the main (and pretty much the only) reason txns must be in the same container as the parent.

**Comment by tkaitchuck** [comment]
> I'm not sure how we would expose it via the API
I don't think we need to expose anything differently than it is now. We can work out at merge time how we want to do the merge. I don't see any reason that needs to be decided in advance.

**Comment by fpj** [comment]
> Step 1 of the merge happens in the SSS metadata and read index. The concat to tier 2 happens much later (seconds, maybe minutes). During this time the data in the txn must be readily available for reading in the parent segment. This is the main (and pretty much the only) reason txns must be in the same container as the parent.

I'm concerned that if we go deep on this point it will consume this thread and it will derail the issue discussion, but I want to at least highlight the problem as I see it. The main point I'm worried about with respect to txn segments merging to specific parents rather than any set of parents is txn semantics (client API). We now have this funny "grace period" for txns when a scale event kicks in, which is undesirable. I'd really like to get rid of that txn timeout.

> I don't think we need to expose anything differently than it is now. We can work out at merge time how we want to do the merge. I don't see any reason that needs to be decided in advance.

I read it again and from this comment and the second pass, it sounds like there is no real API change needed as there is no change in semantics. I originally thought you're talking about providing different ways of merging.

If I understand your proposal right this time around, the problem I see is that at a high rate, based on this observation:

> We could treat the transaction commit as a metadata operation in the controller. It would seal the transaction segments and the stream segments, add the transaction segments to the end of the metadata

we will be sealing and stitching a lot of segments. If txns are short and come at a high rate, isn't this going to cause a couple of things to happen:

- Clients will have to contact the controller very frequently
- Segment store will have to create a very large number of segments for streams individually over time

I'd need to convince myself that utilization of resources is acceptable.

**Comment by bhargav-gulavani** [comment]
As I understand the proposal, its key merit is that it helps us do away with scale grace period. However, as @fpj has pointed out, it does lead to lots of segments being sealed and stitched if the txn commit rate is high. Moreover, it causes glitch on the readers and writers both.

However, I believe sealing existing segments is not really necessary. We could keep all advantages of the scheme by instead adding a special event, _TxnMarker_, to all the currently active segments of the stream. Each such TxnMarker has following two pieces of information (1) the segment identifier, so as to route readers to appropriate segment container for reading events in that transaction segment, and (2) transaction segment key range, so as to correctly synchronize readers if key range of transaction segment is not subsumed by the key range of stream segment. While completing transaction commit operation, for each transaction segment _s_ having key range _k_, we add the special marker event _TxnMarker(s, k)_ to each stream segment whose key range overlaps with _k_.

In order to ensure that the set of _TxnMarkers_ inserted form a consistent cut, we do need to appropriately synchronize (a) insertion of these TxnMarkers across currently active stream segments and (b) segment seal operations on currently active segments arising due to stream scaling. This can be achieved by maintaining the sequence of pending TxnMarkers on the current set of active stream segments, aka stream _epoch_.

This scheme does entail changes in readers, because they (a) need to go read a different segment, possibly residing in a different segment container on encountering a TxnMarker, and (b) need to synchronize appropriately on _TxnMarker_ events in addition to segment seal events. However, writers do not need to be changed in this scheme, and we still can do away with scale grace period.

**Comment by tkaitchuck** [comment]
>I read it again and from this comment and the second pass, it sounds like there is no real API change needed as there is no change in semantics. I originally thought you're talking about providing different ways of merging.

I am not proposing any public API change. Merely that when merge is called we make a decision: Has a scale up occurred since the transaction started? If no, we merge exactly as we do now. (This will be the case most of the time. If yes, we temporarily scale back down, then commit, then redo the scale up. (Yes, this is more expensive, but we currently can't do anything in this situation except invalidate the transaction, and a costly commit is better than an impossible commit)

**Comment by andreipaduroiu** [comment]
This was implemented with #2557 and #179
