### ISSUE TITLE
Revisit and consolidate Controller Exceptions 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1367]
**Problem description**
Presently we have a lot of checked exceptions of different type all over the place in controller. 
it is generally a good idea to consolidate them component wise and throw the component exception (e.g. StoreException) and set specific traits and types in the exception using which we callers can handle them. 

**Problem location**
Controller Exceptions

**Suggestions for an improvement**
Consolidate exceptions

**Comment by tkaitchuck** [comment]
Our policy: https://github.com/pravega/pravega/wiki/Contributing#exceptions
is to have one parent exception type and have subclasses for each of the speffic exception types rather than using traits. This allows the caller to handle the exception both generally by catching the parent exception type or specifically by catching the individual types.

**Comment by shiveshr** [comment]
This has been addressed in various PRs and controller has typed exceptions per module.
