### ISSUE TITLE
Transaction commit idempotence

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1401]
**Problem description**
If commit is called twice for the same transaction, the transaction will not be recognized by the controller so a Failed status is returned to the client which in turn throws TransactionFailedException to the caller. This is confusing as the transaction may have committed.

**Problem location**
Client and controller

**Suggestions for an improvement**
We need to retain a record for some time of transactions that committed so we can tell if it failed or not.

**Comment by bhargav-gulavani** [comment]
This problem was fixed in PR #1161. We have also added a bunch of test cases to test idempotence of commit and abort operations as follows.
1. `testTransaction` test in `controller/server/src/test/java/io/pravega/controller/store/stream/ZkStreamTest.java`, and
2. `testTransactionTaskSweeping` in `controller/server/src/test/java/io/pravega/controller/task/TaskTest.java`

If you still observe the problem, could you please attach the repro steps?
