### ISSUE TITLE
Quick performance Test for Tier1

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#1422]
**Problem description**
Currently, there has been a performance improvement needs for Tier 1 layers. Now that https://github.com/pravega/pravega/issues/1330 has been reviewed and merged, we can measure how much improvement has this new change caused. 

**Problem location**
Tier 1 Performance

**Suggestions for an improvement**
Please run some of the previous test using normal instances on AWS. (No expensive instances pls)

**Comment by fpj** [comment]
To complete this issue, we should publish some numbers as a result of the exercise.

**Comment by andreipaduroiu** [comment]
I don't know how much value we can get out of this exercise. To do a real comparison, we need to run the test with the old (synchronous) way of writing to BK and then again with the current way. If we just run the test with the current code and compare with our results from 6 months ago, we will not be able to compare apples to apples because a lot of other things changed which count potentially affect performance.
