### ISSUE TITLE
Segment Container Fails to start due to DataCorruptionException while scaling up Segement Store service instances

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#1428]
**Problem description**
Segment Container fails to start when SSS is scaled from 1 instance to 3 instances. 
Segment Container 1 fails to start  with the following exception.
`io.pravega.segmentstore.server.DataCorruptionException: Unable to update metadata for Log Operation StreamSegmentAppendOperation: SequenceNumber = 71161, SegmentId = -9223372036854775806, Offset = 0, Length = 90, Attributes = 2`

`Caused by: io.pravega.segmentstore.contracts.StreamSegmentNotExistsException: [Segment 'testAutoScale102956883/testTxnScaleUp/0#transaction.bed5027e32c5415e89a2e91ab04b0879'] The StreamSegment does not exist.
`

When SSS was scaled to 3 instances stream creation failed.
Segment Container 1 failure: (It never came up on SSS-2). It failed with the above exception.
**Problem location**
SSS, while running system test MultiSegmentStoreTest.

**Comment by shrids** [comment]
Attaching details:
[MultiSegmentStoreIssueDetails.txt](https://github.com/pravega/pravega/files/1068039/MultiSegmentStoreIssueDetails.txt)

**Comment by andreipaduroiu** [comment]
The problem was caused by #1330 / #1391. When assigning new Segment Ids, instead of using the Container Metadata's Sequence Number, it was using the value of the sequence number to be assigned during recovery (which during non-recovery was always set to `Long.MIN_VALUE`). Since the latter is not monotonically increasing, it is very likely that after a metadata cleanup, such an ID would be recycled. Based on the logs, it looks like this was just the case. `Long.MIN_VALUE + 2` was deleted (previously), and then it was reused for a transactions.
