### ISSUE TITLE
Reader/Reader Group Metrics

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#1442]
**Problem description**
Currently, there is no easy way to determine a client's ingestion and consumption rates per stream. We can only see the other way around, i.e rates per segment without knowing how many readers/writers are involved. 

**Problem location**
area/metrics
area/client

**Suggestions for an improvement**
Introduce new metrics OR attach a client Id, reader and writer identifications to the existing consumption/ingestion metrics. For example;
```
READER_LATENCY      pravega.client.reader_latency.$scope.$stream.$segment.$client_id.$reader_group_id
READER_BYTES        pravega.client.reader_bytes.$scope.$stream.$segment.$client_id.$reader_group_id
WRITER_LATENCY      pravega.client.writer_latency.$scope.$stream.$segment.$client_id
WRITER_BYTES        pravega.client.writer_bytes.$scope.$stream.$segment.$client_id

// $writer_id or $reader_id = "23gdq29fu20912@11.223.20.166" or in similar format
// where 11.223.20.166 defines where the client is connecting from
// 23gdq29fu20912 defines unique Id created by controller for the reader
```

The benefits of these metrics will 
1. provide detailed view of performance of individual clients per stream
1. provide detailed view of how balanced the readers are consuming
1. help identify failed, stalled or slow reader in a group
1. help identify abuse or misbehavior of specific clients
1. help identify reactions of readers in a group after scaling action occurs 
1. help users to plot graphs and UI elements from the metrics via Graphite, Influx, or any other metrics collector and analyzer. 
1. and so on...

**Comment by fpj** [comment]
@tkaitchuck and I had a discussion about these metrics and we are unclear about a few things:

1. What's latency here for the reader? Latency for the reader is not as meaningful as latency for the writer. If the reader takes a long time to read, then it doesn't mean that it is inefficient, it could be that there was not data to be read. One possibility is that this is referring to end-to-end latency, in which case the metric would be more meaningful, but we don't currently the means to compute as we don't keep track of the ingestion time. It is also unclear whether this should be a metric per reader or reader group. In any case, it would be good to have some clarification on what we are after.
2. Reporting the bytes read per reader might not be very meaningful in the case we contrast with the number of bytes written per writer because writers spread events potentially across all segments while readers are assigned a fixed subset (in the absence of rebalances). An aggregate metrics per reader group might be more meaningful, but I'm not sure, it depends on what kind of experience we are targeting.
