### ISSUE TITLE
Expose reader group and its members via REST API

### ISSUE THREAD

**Issue by bayarsaikhan** [pravega/pravega#1443]
**Problem description**
Reader group details for a stream are not visible to the external users. Lets say if user want to list all readers per a stream, there is no way. It is crucial especially for the use case https://github.com/pravega/pravega/issues/1442

**Problem location**
area/rest
area/readergroup

**Suggestions for an improvement**
Expose reader group details via REST API. For example
```
GET /pravega/stream_id/readers

Response
{
  "stream_1",
  "reader_groups",
  { "reader_group_1",
      { "reader_1", "created_at"
        "reader_1", "created_at"
        "reader_1", "created_at"
      }
  { "reader_group_2",
  ....
  }
}

```

**Comment by skrishnappa** [comment]
@bayarsaikhan readergroups are not a property of a stream. Since readergroup is over a collection of streams we could have the following REST APIs
1. List all readergroups within a scope
GET /scopes/<scopename>/readergroups
Response
{
  "readergroups" :
    ["groupname" : "group1", "groupname" : "group2"]
}

2. Fetch properties of a specific reader group
GET /scopes/<scopename>/readergroups/<readergroup name>
Response
{
  "groupname" : "group1",
  "onlinereaders" : ["readername" : "reader_1", "readername" : "reader_2"],
  "streams" : ["streamname" : "stream1", "streamname" : "stream2"]
}

**Comment by bayarsaikhan** [comment]
@glounder what do you think?

**Comment by glounder** [comment]
Looks good except for the list response.  It should return an array of readergroup objects (or a subset of the object).  So it would look something like:

```
{
"readergroups" :[{
    "groupname" : "group1"
  }, { 
    "groupname" : "group2"
  }]
}
```

Same with the list of streams.  It should be an array of objects that are a subset of the Stream object (scopeName and streamName) from the existing api calls.

**Comment by glounder** [comment]
Is there any point in making an API call to get an individual reader?

GET /v1/scopes/<scopename>/readergroups/<groupname>/readers/<readername>

It depends if there is reader information that would make the call to get the readergroup too large or slow.
