### ISSUE TITLE
Cleanup Counter Names

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#1488]
**Problem description**
If you look in `io.pravega.shared.MetricNames` you will see tons of inconsistencies across the names of various counters. Let's have a look at these and at least make them consistent.

Some examples:
```
public static final String SEGMENT_CREATE_LATENCY = "segment_create_latency_ms"; // Timer
public static final String SEGMENT_READ_LATENCY = "segment_read_latency_ms";     // Timer
public static final String SEGMENT_WRITE_LATENCY = "segment_write_latency_ms";   // Timer
public static final String SEGMENT_READ_BYTES = "segmentstore.segment_read_bytes";            // Dynamic Counter
public static final String SEGMENT_WRITE_BYTES = "segmentstore.segment_write_bytes";          // Dynamic Counter
public static final String SEGMENT_WRITE_EVENTS = "segment_write_events";                     // Dynamic Counter
```

**Comment by Abhijeet-Jadhav** [comment]
Metrics were recently renamed to fix https://github.com/pravega/pravega/issues/1370.
The emitted metrics names are consistent w.r.t. https://github.com/pravega/pravega/issues/1370#issuecomment-307305905.
But, the internal names aren't consistent because statsLogger takes name as parameter and dynamicLogger doesn't. Will try to make MetricsName.java naming consistent through this issue.
