### ISSUE TITLE
Scaling-Events REST API should report the last Scaling Event before the "from" timestamp

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#1513]
**Problem description**
For our scaling test, the "getScalingEvents" API call returns the stream creation event (i.e. the very first scaling event that happened to the stream) instead of the last scaling event before the "from" timestamp.
The segments listed in that first event are long gone (sealed) by the "from" moment, so there is no information for us (users) to recreate the stream segments that existed at the "from" timestamp.

**Problem location**
We are using a build with the last changes from #1498 (includes "getScalingEvents" REST API from #1446 ) 

**Suggestions for an improvement**
The "getScalingEvents" API call with "from" and "to" query parameters should return a list of scaling events that include 
(i) the _**last**_ scaling event that happened to the stream _**before**_ the "from" timestamp,
and 
(ii) a list of scaling events that happened between the "from" and "to" timestamps.

**Comment by fpj** [comment]
I think there is a bug in this line as if keeps updating the reference event for anything that has a timestamp less than `from` instead of computing the greatest lower bound:

https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java#L446
