### ISSUE TITLE
Handle connection failure to the controller

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#1548]
**Problem description**
Connections from the client to the controller sometimes fail. Either due to a controller instance being down or an intermittent failure. There is no logic on the client side to retry requests in the event that they cannot connect to the controller instance that was assigned, nor is there any logic to remove a down host from the list that will be attempted. This results in a large fraction of all calls failing if even a single controller instance is offline.

**Problem location**
In controllerImpl the controller is initilized via:
```       
 this(ManagedChannelBuilder.forTarget(controllerURI.toString())
    .nameResolverFactory(new ControllerResolverFactory())
    .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance()).usePlaintext(true));
```
Which naively returns controller instances in a RobinOrder. With no support for removing instances that have failed.

**Suggestions for an improvement**
We will need to create a custom LoadBalangerFactory, because apparently gRPC doesn't even implement that basic support.

**Comment by tkaitchuck** [comment]
This is somewhat relate to #1531 and #1485

**Comment by fpj** [comment]
I agree that we should probably do something smarter, but even if we have one faulty controller on a list with multiple addresses, we should still be able to reach a working controller, right? Or, are you saying that we are not even re-trying a failed request and blocking?

**Comment by tkaitchuck** [comment]
We are not retrying at all so the exception due to not being able to connect to the down host fails the call completely.

**Comment by skrishnappa** [comment]
@tkaitchuck have you observed this behavior? If yes need details to debug why gRPC is continuously failing RPCs even if at least one server is up, since this is not the expected behavior.

There is no internal retries in the gRPC client on RPC failures (i.e. only if RPC was attempted to a connected server), and I guess that's how low level clients should behave. IMO this is expected since only the application can decide if retrying on RPC failures is safe or not. There could be corner cases when server was down but client hadn't yet detected this and fails an RPC, but this could happen once (maybe few if there are some corner race cases in the gRPC load balancer code) for a failed server but shouldn't have been observed subsequently. 
With the current load balancer implementation RPC to this server will not be attempted until a successful network connection is re-established, hence no more failures should have been observed due to this failed server (assuming there is at least one other server with valid tcp connection).

If we really want retries in the ControllerImpl client on RPC failures, we could implement it as a layer over the gRPC client (not by writing a custom loadbalancer). Currently the controller client is a simple wrapper over the gRPC client. It was assumed that the pravega client (which uses the controller client) already has retry logic in place.

**Comment by fpj** [comment]
As I see it, there are two cases:
1- gRPC doesn't even get to establish a connection to the server. In this case, it sounds safe to re-try.
2- gRPC establishes a connection, but fails midway and we don't know the outcome.

With case 2, it sounds right to fail and leave to the app to determine what should be done next, but case 1 sounds like a candidate for retrying if we can make the distinction.

The other issue that @tkaitchuck is bringing up is that we aren't removing servers that are known to have failed, or at least a connection to them have failed. This is a fairly tricky thing to do because:

a. We don't want to remove a server due to one connection failure as it could be a temporary issue. But, if it is not one failure, then how many?
b. How do we bring back servers that we removed? Or is it the case that once removed we don't bring them back?

Using the scheme we currently have (along with the changes in #1543 ) and going around the list in the case of an initial connection failure sounds like a reasonable way.

**Comment by skrishnappa** [comment]
>> The other issue that @tkaitchuck is bringing up is that we aren't removing servers that are known to have failed, or at least a connection to them have failed

We shouldn't be removing the server from the list and that is exactly what gRPC is doing. It correctly ignores it until a connection is established to it. So a. and b. you mentioned should be an issue.

**Comment by skrishnappa** [comment]
This issue seems to have been filed in context of a system test failure. Following is the analysis and reason for the controller client failure seen in the test (have attached the system test client log for reference):

Summary:  System test was started with 3 controller instances, but the controller client was configured with only 2 controller servers. So when the controller was scaled down to 1 service, the controller client couldn't send any more RPCs since the 2 configured controller servers was stopped, hence you see the client RPC failure logs even though one controller server (not configured with the client) is up and running.

From client logs:
Controller marathon resposne (see 3 instances of controller configured for the scale request):
    "id": "/controllerfailover1",
    "instances": 3,
But the controller client was configured with only 2 instances:
  2017-07-07 12:14:00,468 876  [main] INFO  i.p.t.s.MultiReaderWriterWithFailOverTest - Pravega Controller service instance details: [tcp://172.16.24.16:9092, tcp://172.16.24.16:10080, 
  tcp://172.16.24.13:9092, tcp://172.16.24.13:10080]
2017-07-07 12:14:00,471 879  [main] INFO  i.p.t.s.MultiReaderWriterWithFailOverTest - Controller Service direct URI: tcp://172.16.24.16:9092,172.16.24.13:9092

If the controller client was configured correctly with 3 endpoints, we shouldn't have observed this issue. 

@shrids @Prabha-Veerubhotla this seems like an intermittent issue, since this we haven't seen this in the other multi-controller tests. We probably have to assert or wait until the client can fetch all controller server details (after a scale service call) before configuring the controller client.

[server.zip](https://github.com/pravega/pravega/files/1136005/server.zip)

**Comment by tkaitchuck** [comment]
>With the current load balancer implementation RPC to this server will not be attempted until a successful network connection is re-established, hence no more failures should have been observed due to this failed server (assuming there is at least one other server with valid tcp connection).

If you look at the code, it simply does not do this. Contrary to their documentation.

>If we really want retries in the ControllerImpl client on RPC failures, we could implement it as a layer over the gRPC client (not by writing a custom loadbalancer). Currently the controller client is a simple wrapper over the gRPC client.

Yes. Agreed. It should be in ControllerImpl not in the loadBalancer. (I don't think that is even possible)

>2- gRPC establishes a connection, but fails midway and we don't know the outcome.
With case 2, it sounds right to fail and leave to the app to determine what should be done next, but case 1 sounds like a candidate for retrying if we can make the distinction.

We should be able to retry these also. The operations on ControllerImpl are all supposed to be idempotent.

**Comment by skrishnappa** [comment]
>> If you look at the code, it simply does not do this. Contrary to their
documentation

The code seems correct, I have tested this behavior since I initially
implemented this too. Verified this again to reconfirm.
From an implementation perspective, it uses a concept known as picker,
which picks only subchannels (among the configured server transport
channels) which are in a HTTP/2 ready state (i.e. connected). If this
channel's network state changes (rst or close) then its removed from the
picker's list. So next time it will not be attempted. Only happens when its
added back to the pickers list (i.e. once it achieves a HTTP/2 ready state
on a successful reconnect)

**Comment by skrishnappa** [comment]
@tkaitchuck To clarify the implementation following are the code references where the server with failed connection is temporarily removed from the list as described earlier:
io.grpc.util.RoundRobinLoadBalancerFactory
updatePicker() -  calls filterNonFailingSubchannels() to update and fetch only channels which are in ready state.
updatePicker() is called whenever there is a transport state change, you can verify this from the reference in the code. 
The existing ControllerImplLBTest exercises all these code paths. You can verify it by putting break points in your IDE and running the unit tests.

Also please check the update to the earlier failover test case to verify that no RPC calls fail after a server is brought down (using the same controller client configured with the failed server) - https://github.com/pravega/pravega/pull/1543/commits/6e1f142c37cb59245b178b7678a4cac6f0bb7f80

**Comment by shrids** [comment]
@skrishnappa Performed the following tests repeatedly on a test cluster. 
 
```
  Service controllerService = new PravegaControllerService("controller", zk.getServiceDetails().get(0));
        if (!controllerService.isRunning()) {
            controllerService.start(true);
        }
        final List<String> uris = controllerService.getServiceDetails().stream().filter(uri -> uri.getPort() == 9092).map(URI::getAuthority)
                .collect(Collectors.toList());

        System.out.println(uris.size()); // size is always 1 since there is one instance
        controllerService.scaleService(4, true);
        final List<String> urisAfterScale = controllerService.getServiceDetails().stream().filter(uri -> uri.getPort() == 9092).map
                (URI::getAuthority)
                .collect(Collectors.toList());

        System.out.println(urisAfterScale.size()); // size is always 4 since there are 4 instances.
```

There is never a case were the uri size is less than the scale count of the service. It always matches to the number of instances of the services.

**Comment by skrishnappa** [comment]
@shrids please check the attached the logs, the following line indicates only 2 controller instances were returned (unless there is some other explanation for this):
2017-07-07 12:14:00,468 876 [main] INFO i.p.t.s.MultiReaderWriterWithFailOverTest - Pravega Controller service instance details: [tcp://172.16.24.16:9092, tcp://172.16.24.16:10080,
tcp://172.16.24.13:9092, tcp://172.16.24.13:10080]
2017-07-07 12:14:00,471 879 [main] INFO i.p.t.s.MultiReaderWriterWithFailOverTest - Controller Service direct URI: tcp://172.16.24.16:9092,172.16.24.13:9092

This is not observed in other tests so its an intermittent issue. We don't have to wait for a repro to confirm I guess. If this is something that should never have happened then lets add an assertTrue(uriCount == serviceCount) in the test case after every scale operations. But since we have observed the issue once, we could probably wait until the uri count matches (maybe in a loop for a bounded time and then assertFalse if the condition is not met).

**Comment by shrids** [comment]
Steps performed by  `List<URI> io.pravega.test.system.framework.services.Service#getServiceDetails()`  :
```
-  get a list of all tasks for a given service id.
-  get the ports configured for each of the task.
-  create URI with each port and the host on which the task is running.
```
So the number of URI depends on the number of tasks inside a service and the number of ports configured for each task. i.e. number of tasks * number of port/task

Now, the service instance count is not used in the implementation of getServiceDetails api. Hence it is not straightforward to implement this assert inside the getServiceDetails(). It is much simpler for the assert to be placed in the system test file.
