### ISSUE TITLE
Controller failover test should use startScale instead of asynchronously calling scaleStream

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#1844]
**Problem description**
Controller failover test wants to ensure scale is started on one controller instance and completed on another. For this it needs an ack from controller that scale has indeed started. 
The test is presently calling scaleStream method asynchronously, which will not complete until all existing txns are aborted. 
However, test does not know if controller had started the scale or not because it makes the call asynchronously. And it starts controller failover.. This means the test can fail because the controller instance receiving the manual scale request may have been killed before it could start the scale.  

**Problem location**
ControllerFailoverTest

**Suggestions for an improvement**
Use startScale api and wait for response from controller before calling failover.

**Comment by fpj** [comment]
We have seen one test case error due to this, and the key log messages are:

```
2017-09-05 16:28:48,478 94161 [grpc-default-executor-0] ERROR i.p.c.stream.impl.ControllerImpl - failed to start scale {}
io.pravega.common.util.RetriesExhaustedException: java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE
```

I understand that the the call is not making to the controller instance before failover, but given that we retry, shouldn't it have made to the controller instance available post-failover? From the logs, it looks like it exhausted the retries, so it wasn't able to find a new controller.
