### ISSUE TITLE
PDP 19: Pravega Retention

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1946]
**Problem description**
Pravega Design Proposal for stream data retention.

See https://github.com/pravega/pravega/wiki/PDP-19:-Pravega-retention

**Problem location**
Client, Controller, Segment Store.

**Suggestions for an improvement**
See the PDP page for more detail.

**Comment by shiveshr** [comment]
> Tier2 Data truncation.
> Controller Managed
> Controller rolls over segments: it will seal existing active segments and begin new ones (1:1 split) when the segments reach a certain size or some time elapsed.
> 
> Pros: already a mechanism for this in the Controller, with most steps already implemented
This can effectively be modeled as a scale operation with input to seal and recreate identical segments. 

> Cons:
> How to handle open transactions? How do we roll them over. We can't simply rename them, since that means they'd be owned by a different Container and it's possible there's unflushed data in Tier2 which could lead to data loss.
If we model above as a simple scale operation, we dont have to do anything special. Transaction and scale interference will take care of this aspect. 
Also, once we have "rolling-transaction", this concern will go away. 

> Some special (internal) Streams need exactly one segment. They cannot function with more than one.
Only (internal) stream with requirement for exactly one segment is 'reader-group'. 
If we make "automatic" retention optional, then such internal streams can choose not to have any retention policy. Is that acceptable?

Another con:
We will end up sealing and creating new segments for streams that have opted out of scale. 
This will create unnecessary noise in scale notification and UI graphs which will show new segments. We may have to either special case to hide these segments and some flag indicating they are "recreated" segments so that notifications and UI can special case them.

**Comment by shiveshr** [comment]
`CompletableFuture<StreamCut> getStreamCut()` 

getStreamCut should be a client local api with no involvement of controller. ReaderGroup has access to RG internal stream and state synchronizer. 

`CompletableFuture<Void> trimStream(String stream, StreamCut cut)

trimStream should be a controller api. Upon receiving this call, controller orchestrates truncation workflow across different segments.  


> We can have such a call available to both readers and writers, but it belongs naturally on the reader side as cut can represent some point up to which all has been read. A reader group can use a state synchronizer to coordinate the construction of a stream cut that is consistent with the progress of all readers. If we decide to provide such a call on the writer side as well, then we will need to either:
> 
> Coordinate writers and have some notion of writer group
> Have the controller putting such a stream cut object together
>
It is not clear what a writer based stream cut could look like without a writer group coordinating among themselves.
One simpler alternative is to simply expose a REST api to generate a new latest point in time StreamCut.  
something like:
`CompletableFuture<StreamCut> generateStreamCutNow(StreamId stream)`

This REST api can be invoked by the application at any point and is not tied to any writer or writer group.
 
Controller should take active segments from metadata store and asks segmentStores for latest offset for these segments and compose a StreamCut. 
 
(Note: This can only compute a stream cut corresponding to currentTime. We cannot do historic stream cuts because we dont maintain time index on segments. But "now" is possible as we just need to pick latest offset across active segments. )

**Comment by shiveshr** [comment]
> We can have such a call available to both readers and writers, but it belongs naturally on the reader side as cut can represent some point up to which all has been read. A reader group can use a state synchronizer to coordinate the construction of a stream cut that is consistent with the progress of all readers. If we decide to provide such a call on the writer side as well, then we will need to either:
> 
> Coordinate writers and have some notion of writer group
> Have the controller putting such a stream cut object together
>
It is not clear what a writer based stream cut could look like without a writer group coordinating among themselves.
One simpler alternative is to simply expose a REST api to generate a new latest point in time StreamCut.  
something like:
`CompletableFuture<StreamCut> generateStreamCutNow(StreamId stream)`
This REST api can be invoked by the application at any point and is not tied to any writer or writer group.
 
Controller should take active segments from metadata store and asks segmentStores for latest offset for these segments and compose a StreamCut. 
 
(Note: This can only compute a stream cut corresponding to currentTime. We cannot do historic stream cuts because we dont maintain time index on segments. But "now" is possible as we just need to pick latest offset across active segments. )

**Comment by fpj** [comment]
> CompletableFuture<StreamCut> getStreamCut()
>
> getStreamCut should be a client local api with no involvement of controller. ReaderGroup has access  to RG internal stream and state synchronizer.

We already produce stream cuts for checkpointing purposes internally for reader groups. It shouldn't be difficult to use the same or a similar mechanism to obtain a stream cut.

But, I'd say it depends on the semantics we want to give to it. Asking the controller to collect the last offset of all current segments and put them in a stream cut object would, for example, enable calls from the writer as well. The downside of having it done in the controller is that it has no correlation to what has been read or written.

**Comment by fpj** [comment]
> > Tier2 Data truncation.
> > Controller Managed
> > Controller rolls over segments: it will seal existing active segments and begin new ones (1:1 split) when the segments reach a certain size or some time elapsed.
> > 
> > Pros: already a mechanism for this in the Controller, with most steps already implemented
> 
> This can effectively be modeled as a scale operation with input to seal and recreate identical segments.

There is at least one issue with revisioned streams I'm aware of. Revisioned streams rely on the ability of contrasting offsets to determine whether a conditional append should be successfully performed or not. If we roll the segment, then we will be resetting the offset and the condition to apply an append will have its parameters messed up.

If we are to follow this strategy, which at a high level seems to work nicely, then we will need to sort out corner cases like this one.

**Comment by andreipaduroiu** [comment]
From my POV, we can do rolling segments in the Segment Store without sacrificing too  much. However, we can't get away without having multiple sub-segment files in Tier2, in addition to a header file per segment. 

However, if we could achieve this 100% in the controller, that would be a lot more desirable from my POV.

@tkaitchuck Is there no way that Reader Groups can deal with this situation?

**Comment by shiveshr** [comment]
@fpj

> Asking the controller to collect the last offset of all current segments and put them in a stream cut object would, for example, enable calls from the writer as well. The downside of having it done in the controller is that it has no correlation to what has been read or written.


wrt getStreamCut, i mentioned two flavours: getStreamCut (client local, on readerGroup) and getStreamCutNow (controller REST)

The reads are at least correlated to the stream cut using readergroup local api.
Since we dont have a notion of writerGroup at this point, so we wont try to solve writes correlation to Stream Cut. 
But give a general streamCutNow api on controller that can be used by application invoked at their time of choosing.

**Comment by shiveshr** [comment]
@fpj @andreipaduroiu 
do we intend to use streams exposing `conditional writes` to beyond State Synchronizer. 

IMO we `conditional writes` are a good primitive that can have a lot of uses. And we should not limit is future application because of a design choice for retention. 
 
So if conditional writes will strictly require that the segment never scale, then rolling segments scheme using `scale` should be avoided.

**Comment by fpj** [comment]
> wrt getStreamCut, i mentioned two flavours: getStreamCut (client local, on readerGroup) and getStreamCutNow (controller REST)

Makes sense. We could have one way of getting a cut that is equivalent to taking a checkpoint of the state of the reader group, where state refers to the positions across the group. I don't see a reason for the implementation of this call to be difficult to implement given our current implementation of checkpointing.

We could have as you suggest an additional call that is answered by the controller and does not necessarily correspond to where the readers are in the stream.

> do we intend to use streams exposing conditional writes beyond State Synchronizer.

Revisioned streams are exposed, but we don't have concrete use cases beyond the state synchronizer that I'm aware of. I'd rather not close this door, though. The revisioned stream is an interesting and powerful concept.

> So if conditional writes will strictly require that the segment never scale, then rolling segments scheme using scale should be avoided.

I wouldn't say that it is a "requirement" that it doesn't scale, but if it does scale, then it will have to at least solve the problem with offsets/length mentioned here in a decent way:

https://github.com/pravega/pravega/issues/1946#issuecomment-335162072

**Comment by tkaitchuck** [comment]
Yes, there is no reason we should limit conditional writes.
Additionally limiting them to StateSynchronizer doesn't actually solve the retention problem completely, because we still do need to truncate the StateSynchronizer segments to free storage space.

**Comment by andreipaduroiu** [comment]
To add some closure to this conversation. We will implement Tier2 Segment truncation via Rolling Segments (PR #1980), which is a solution that will still allow conditional writes. In addition, each segment can have its own rolling policy (granularity of truncates), so internal segments can be cut with greater precision than larger, user-segments.
