### ISSUE TITLE
PDP 21: Protocol versioning

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1948]
**Problem description**
Pravega Design Proposal for protocol versioning.

See https://github.com/pravega/pravega/wiki/PDP-21:-Protocol-revisioning

**Problem location**
Wire commands.

**Suggestions for an improvement**
See the PDP for more detail.

**Comment by fpj** [comment]
@tkaitchuck Some questions and observations about the proposal section:

> To support supplemental information, we can add fields to the existing wire protocol types. These will be implicitly ignored if either side is running older code.

It may sound obvious, but this seem to be making the assumption that a new field is added always at the end of message. If we add it in the middle or do any other kind of reordering of fields, then it becomes incompatible.

> Upon connecting the client sends the range of versions it supports and the server replies with its range.

Why doesn't the server simply return the highest version it supports and that overlaps with the range of the client? In fact, if we make the assumption that the version of the server must be higher, then the answer should be either the max of the client or no version at all (no compatibility).

> If we increment the version number of the API every time a new API is added, then when support is added on the server side for the new message type it increments the upper end of it's supported range. The client can use this version number to detect if it can invoke the new API.

If we make the assumption above, then a client will always be able to invoke any API call it knows about.

**Comment by tkaitchuck** [comment]
> It may sound obvious, but this seem to be making the assumption that a new field is added always at the end of message. 

Yes. Updated to call this out explicitly.

> Why doesn't the server simply return the highest version it supports and that overlaps with the range of the client?

If each sends their own range as soon as the connection is established it cuts the latency of setting up the new connection. I've clarified this in the PDP.

**Comment by fpj** [comment]
@tkaitchuck thanks for the updates. I have made some edits to the proposal section to clarify a few points.

Another pointer that needs clarification is the following. It is a fair assumption to make that the server is running the same or a newer version. The reason I'd like to make that assumption is to be able to simplify the code on the client side so that the client doesn't need to deal with older versions of the server. You don't seem to want that assumption, and I can understand that it gives flexibility not to assume it, but again, it is reasonable and over time it is likely to pay off. 

If we make such an assumption, then, for example, in PR #1944, we wouldn't need to perform a length check. It is fine now that we don't have many of those, but over time, we could end up with lots of if checks like that, making the code messy.

If you feel it is very important not to constrain this way, then I can accept for now that we assume any combination of versions for client-server interactions, and revisit it at some point in the future whether we should revert the decision for now.

**Comment by tkaitchuck** [comment]
> Another pointer that needs clarification is the following. It is a fair assumption to make that the server is running the same or a newer version.

I don't think we can always assume that in all cases. In fact in some orgs that might be quite common. After all taking down a service to upgrade it is disruptive, and they may not wish to do so unless they care about some new feature of bugfix. Whereas clients may well be upgraded automatically every time the client application is built. So it's quite possible that the client gets deployed with support for some new feature before the server. 

If we were to make that assumption in #1944 we would still want the length check, because the parameter is not mandatory and may be omitted. In this case it is when there is no previous ack.

Certain features may need to be deployed server first though. For example if we add a new API to the client that depends on a new API on the server, obviously the server must be upgraded before the client can call it. So it is reasonable for the client logic to expect that the server is sufficiently up to date to support the API if it has been invoked.
