### ISSUE TITLE
Bug fix and test case for ReaderGroup.unreadBytes

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#1992]
**Problem description**
I couldn't find any unit test or integration test exercising `ReaderGroup.unreadBytes`. While writing one, I got an NPE, which I fixed by adding a call to `fetchUpdates` in the implementation of the `unreadBytes` calls. The next problem I faced is that the call to `getSuccessors` given a stream cut is not implemented in `LocalController`.

**Problem location**
Client, tests.

**Suggestions for an improvement**
Add test cases.

**Comment by tkaitchuck** [comment]
The problem comes down to what do we do when a reader dies and comes back with no position object. 
In theory a reader is supposed to persist their segments at every checkpoint, and perhaps more often.
If they don't it is hard for us to infer where we should resume from. 

Right now the semantic is that we resume from the offset in each segment at the time the segment was assigned to them. This is equivalent to the assumption that no progress was made on any of the segments they still own, but that segments that have been released to other readers were fully read and processed. This is obviously inconsistent. But enforcing this is why the offset in assigned segments is never advanced. 

We could instead make a different assumption and assume they processed all the events before the last checkpoint and none after it. This would provide a consistent point for the presumed failure. Which may be before or after the true point where no further data was processed. It would have the effect that the offset in assignedSegments would be updated on the getNextEvent following a checkpoint, even if no segments are reassigned.
