### ISSUE TITLE
Readers should handle deleted segments following a truncation. 

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#2017]
**Problem description**
Currently, when we truncate a stream, we delete segments that precede the streamCut. 
There could be existing readers reading from these deleted segments. 

**Problem location**
Client.

**Suggestions for an improvement**
Readers should be able to handle a truncation and move on to reading data post truncation point.

**Comment by fpj** [comment]
There are two possibilities for this issue:
- Reader tries to read truncated data on a `fetchEvent` call (event pointer)
- Reader tries to read truncated data on a `readNextEvent` call

The first should always throw an exception. If the event is there, then there is nothing really we can do. For the second case, we have discussed a few options:

1. Have a configuration option that enables the application to determine whether it wants to silently jump to the current head or error.
2. Always throw, in which case, if the the application is interested in jumping straight to the current head, then it can simply ignore the exception.
3. Instead of throwing, we can have a boolean flag as part of the `EventRead` object to indicate that the reader attempted to read truncated data.

My understanding in our offline conversations is that we prefer option 2 right now to reduce the number of configuration options. Compared to option 3, requesting truncated data should really be an exceptional situation as such it calls for an exception rather than a boolean flag.
