### ISSUE TITLE
Handle too many attributes error in Client and PravegaRequestProcessor/AppendProcessor

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#2239]
**Problem description**
Issue #2233 and PR #2238 enforce a (new) maximum limit on attributes on the Segment Store side, for protection purposes. Should an `append` or `updateAttributes` request have an effect of exceeding this limit, the request will be failed with `TooManyAttributesException`.

**Problem location**
Client, PravegaRequestProcessor, AppendProcessor.

**Suggestions for an improvement**
Think of a proper handling for this exception and what could be done.
Ideas:
- If this is due to too many writers
    - Figure out a way to cleanup attributes to long-dead writers
    - Auto-seal the segment and do a 1:1 split to another segment. That will clear all writer attributes on the old segment.
- If this is not due to writers (we do not yet have this use case)
    - Bubble up the exception to the user?

**Comment by fpj** [comment]
Responding to the points that @tkaitchuck made [here](https://github.com/pravega/pravega/pull/2238#issuecomment-357049328):

> I'm not sure how the client could handle it. The only real way we could is to have a 1:1 scaling event, but to keep the metadata consistent, that would need to be invoked by the controller.

Being able to trigger 1:1 scaling for segments might have additional benefits, like we have talked about before. One example is when we plan to use the stream data for batch processing, so that we can have more parallel segments to read from.

But, let me see if I understand correctly why you are suggesting it. If we have a 1:1 scaling, then only the active writers will re-register their ids, which should immediately drop the unused ones. This would cope with the case of a large number of inactive ids, but not with the case of a large number of active ones (more below).

> It gets more complicated if the attribute that triggers the exception is not the result of adding a new writer, but is rather some built in attribute. In such a case we might not even be able to seal the old segment to create a new one and the stream would become unwritable.

In this case, we need to make sure we always have room to write built-in attributes so that we can at least seal a segment. @andreipaduroiu do you agree?

> I think we should have the lower cap that generates the exception be specific to dynamic attributes. At least then it is manageable. We could then have an api on the controller that the client could invoke to have it look into the segment. (It would have to be idempotent as it would likely be called by many writers at once)

I'm not sure what you mean with "have a look at the segment"

> On the whole however such a workaround seems rather silly. If we invoking the controller to create a new segment and the server is holding onto both the metadata for the new segment and the old one, the amount of data the service is dealing with is strictly larger. All we've done is generate a lot of network traffic and new code paths on the controller and client, to divide a map in the server into two maps.

It is true that it is strictly larger, but in principle such cases should be rare. If we start seeing this a lot, then I'd claim we have a design issue. I'm saying this under the assumption that we will fix the client to avoid creating tons of writer ids unnecessarily.
 
> It's well worth having a metric on this, and fixing the bugs that are causing this huge inflation of writerIds that it is currently tracking. 

Agreed on both proposals.

> But if after we've fixed these bugs there still end up being a large number in production, say because there actually are that many writers, then I think the correct thing to do would just be to handle the larger number. A specialized code path in the client to try to compensate is only going to lead to problems.

Agreed, my sense is that the number of writer ids we had provisioned for sounds pretty reasonable. I dot not foresee in the short term applications with tens or hundreds of thousands of writers simultaneously active. I do think it is possible that applications legitimately bring up and down writers over time, but right now, I'm not convinced that we we should provision for a very large number of active writers. It is clear that if this assumption is incorrect, we might need to go back to design.

**Comment by andreipaduroiu** [comment]
This has been fixed with Extended Attributes sometime last year.
