### ISSUE TITLE
Pravega Security: pick up `validateHostName` from a configuration setting for Pravega Internal communication

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2336]
**Problem description**
From comment: https://github.com/pravega/pravega/pull/2175#discussion_r170793177
Currently the hostname validation is always turned on for Pravega Controller to SegmentStore communication. It should be possible to enable/disable it from the configuration.

**Problem location**
Pravega controller and segmentstore `ClientConfig` object creation.

**Suggestions for an improvement**
Pick up the choice from a config.

**Comment by EronWright** [comment]
Seems like a simple matter, but keep in mind that hostname verification is necessary whenever a broad truststore is in use on the client.   Otherwise the client will be too willing to make a TLS connection to a man-in-middle.  The legitimate scenario for disabling hostname verification is when the client truststore is tailored to a specific certificate.

**Comment by arvindkandhare** [comment]
@EronWright yes, you are right. The impact of setting this to false on enabling man-in-the-middle is significant.
