### ISSUE TITLE
Bounded processing using ReaderGroup API

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#2367]
**Problem description**
The ReaderGroup API should support bounded processing of a subset of the input stream(s).   Ideally a start and/or end position could be supplied for each stream.   The position data would be of type `StreamCut`.

The reader group would start at the supplied start position, or at the earliest possible position if not specified.

The reader group would stop at the supplied end position, or continue to tail the stream indefinitely if not specified.

**Problem location**
ReaderGroup API

**Suggestions for an improvement**
1. Consider deprecating `ReaderGroupConfig::startingTime` parameter.
2. Add a start and end position to `ReaderGroupConfig`.  For example:
```java
StreamCut start1,end1,start2,end3 = ...;

return ReaderGroupConfig.builder()
  .stream("stream-1", start1, end1)  
  .stream("stream-2", start2, StreamCut.TAIL)
  .stream("stream-3", StreamCut.HEAD, end3)
  .stream("stream-4")  // implies HEAD-to-TAIL
  .build();
```

3. Consider deprecating the `streamNames` parameter of `createReaderGroup`, since it is redundant given the above config info.  Likewise for `updateConfig`.

**Comment by EronWright** [comment]
Related to:
 - Bounded Processing using BatchClient #2333
 - Stream seeks #2291

**Comment by tkaitchuck** [comment]
In the example it uses:
>  .stream("stream-4")  // implies HEAD-to-TAIL

but above it says: 
> The reader group would stop at the supplied end position, or continue to tail the stream indefinitely if not specified.

But the tail of the stream and continuing indefinitely are not the same thing.

Also HEAD and TAIL are a little more slippery concepts than normal stream cuts because their meaning changes depending on when the call is invoked. This might cause problems. We could easily add an API to get the current head and tail for a given stream and dispense with the constants. 

But there still is the problem that we want both the start and the end to be optional. However that creates an ambiguous signature if we want to overload .stream().

**Comment by EronWright** [comment]
@tkaitchuck good point, let's make it more explicit that the position is unbounded:
```
StreamCut start1,end1,start2,end3 = ...;

return ReaderGroupConfig.builder()
  .stream("stream-1", start1, end1)  
  .stream("stream-2", start2, StreamCut.UNBOUNDED)
  .stream("stream-3", StreamCut.UNBOUNDED, end3)
  .stream("stream-4")  // implies UNBOUNDED,UNBOUNDED
  .build();
```
