### ISSUE TITLE
PDP 28: Cross routing key ordering

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2372]
**Problem description**
See https://github.com/pravega/pravega/wiki/PDP-28:-Cross-routing-key-ordering

**Problem location**
Pravega reader, Segment store

**Suggestions for an improvement**
See https://github.com/pravega/pravega/wiki/PDP-28:-Cross-routing-key-ordering

**Comment by fpj** [comment]
Thanks for putting this together, @tkaitchuck . A few initial comments:

- We currently  say in the PDP that the goal is best-effort ordering, but I was wondering, based on our conversations, whether we should make it bounded ordering rather than best effort, at least optionally. Bounded here means that two separate segments can diverge by some configured bound. The application could have the option of making it best effort by not setting any bound (or unbounded maybe).
- On the API changes, it says that there will be none, but what about idle readers? In the context of watermarking for Flink, we need to be able to either mark a source as idle or indicate to the idle reader that it needs to emit a watermark. One option related to this PDP is that we indicate to idle readers, or perhaps all readers even, that all segments have advanced its clock.
- One concern I have is with idle segments. Say that I have two segments S1 and S2:
    - S1 and S2 have data for every clock tick up to 25, so they are advancing both at the same speed roughly up to clock tick 25.
    - S1 continues to receive data at the same speed, but segment S2 does not receive any data until clock tick 40.
  My understanding is that the read request will block until S2 has data to return. In the case it is really best effort, we will simply return data from S1, but if we make any effort to wait for S2, then we might be delaying data from S1 unnecessarily. I'm wondering if it is worth responding to read requests upon clock ticks in the absence of data.

**Comment by EronWright** [comment]
Any evaluation of PDP-28 should be done in the context of goals or problem we wish to solve.    It seems there's two high-level goals:
1. improve the order of observation of events to approximate the order of ingestion.
2. improve the correctness of Flink programs with respect to watermarks

PDP-28 effectively tackles (1) but doesn't seem to tackle (2).   I can provide feedback on the applicability of PDP-28 to goal (2), and contrast it with PDP-26, but let's first agree on the goals.

**Comment by tkaitchuck** [comment]
@fpj Yes, there are several potential extensions to this that could be very useful. I want to limit this PDP to the index itself, as that is a big enough on it's own.
@EronWright Yes. We do need a solution for watermarks and idleness. I did not include that as part of this PDP, but we should think about how to solve it.

**Comment by andreipaduroiu** [comment]
@tkaitchuck Let me clarify a few things about how this should work in the Segment Store:
1. We do not encode this in the `DataFrame`. The only purpose of the DataFrame is to batch operations together. It only deals with ranges of bytes, and doesn't understand anything of what's inside. We may want to add this field to the `StreamSegmentAppendOperation` for every append that we want to do and to `MergeTransactionOperation` (for transaction mergers). 
2. The `ReadIndex` will be made aware of this in two ways:
- For newly added data and for Tier1 recovered data: via the `append` method (similar to how you propose it)
- For data loaded from Tier2: the same way you propose it
3. The `ReadIndex` will store this data in a memory-efficient manner, whether it be in RocksDB or in Java heap (TBD).
4. The `StorageWriter` simply writes the data to the file. The `ReadIndex` does all cache management and eviction.

Question: When you mentioned the Newtonian search, did you mean that the `PravegaRequestProcessor` would do that or that you'd want an API in the Store to do the read more efficiently?

**Comment by tkaitchuck** [comment]
@andreipaduroiu Yes. Feel free to correct those details. 
I will add a new section on Transactions and how they relate.

RE search: I assume that will be internal to the store. We don't need to expose the implementation outside of it. In terms of the API I assume it would be just the standard read call but providing some constant in place of the token indicating this is the first read.

**Comment by andreipaduroiu** [comment]
> RE search

**Comment by EronWright** [comment]
Here's some ideas on how to adapt PDP-28 to provide a common foundation for PDP-26 (which deals with ingestion time clock progression) and PDP-28 (which deals with ingestion time ordering).  

1. Make explicit the use of the segment server's wall clock as the source of time values.   This will enable us to expose a meaningful value to the user.
2. Define an interface, `TemporalOperation` that identifies log operations for which a timestamp should be recorded, e.g. `AppendOperation`, `MergeTransactionOperation`.  
3. Ensure that the index is efficient at looking up the latest timestamp for a given offset.  That is, the timestamp of the most recent temporal operation that was applied before-or-at the given offset.

Based on the time index provided in 28, we may, as described in PDP-26, use the time index to annotate reads with a watermark.   By tracking the last observed watermark of each segment in the RG state, we may then produce a global minimum watermark to satisfy goal (2) mentioned above.

**Comment by EronWright** [comment]
@tkaitchuck expanding on the use case and technical details of synergizing PDP-26 with PDP-28:

## Use Case
**Drive the Flink event time clock using the ingestion time of source events.** As a app developer, I'm able to use time-based window functions that organize events by when they were written into the Pravega stream.  For example, I'm able to compute the hourly average temperature based on a continuous stream of sensor events.  

I expect the program to produce accurate results in both a real-time and historical processing context. 

My application is responsible for relating ingestion time to event time; in my case, my sensors write events to Pravega within 5 minutes.  In case a sensor is disconnected for more than 5 minutes, I expect to handle those events as 'late events' using the Flink API.

## Technical Approach
PDP-28 provides a time index in the ingestion time domain. For a given range within a segment, the segment server knows 'when' the corresponding data was written (in terms of the wall clock timestamp of the segment server on which the write occurred).

PDP-26 may leverage the time index as follows.   See PDP-26 for more detail.
1. For each read result (`SegmentRead` response), include a watermark derived from the timestamp of the data included in the response. In particular, calculate the minimum ingestion time of any subsequent data. For example, if a response contains the offset range 0-1000, return the write-timestamp 'X' associated with the data at offset 1000. Since segments are append-only, the client may deduce that any data at offset 1001+ would have an ingestion time of at least 'X'.
2. Terminate 'future' reads (which allow for tailing a segment) after some period of time, by returning an empty `SegmentRead` containing only a watermark based on the current time.   This will ensure that time continues to advance in the face of idle segments.
3. On the client side, track the latest watermark associated with each segment, in reader group state. Update the RG state at checkpoint time as normal.
4. As each reader observes a given checkpoint, compute the minimum watermark across all incomplete segments. This timestamp represents the RG-wide minimum ingestion time of any subsequent events. For example, given two segments 'A' (watermark @ 11:00) and 'B' (watermark @ 11:10), we may assert that all events with an ingestion time before 11:00 have been observed by the reader group.  
5. In the `EventReader`, emit the RG-wide watermark as a new type of `EventRead`, to assert that all events prior to the given watermark have been observed.
6. In the Flink connector, transform the ingestion time watermarks as produced by `EventReader` into the event-time domain, by passing each watermark thru a function, and then emit the resultant timestamp as a Flink watermark.  In most cases, the application may simply subtract a constant 'lag' to transform from ingestion-time to event-time domain. For example, given an ingestion-time watermark of 11:00, subtracting a constant of 5 minutes would assert that all events are written to the stream within 5 minutes of their event time.

**Comment by fpj** [comment]
Thanks for sharing the case, @EronWright . 

There are two options with respect to timestamps:
- The sensors emit samples that include timestamps
- The sensors emit samples that do not include timestamps

If the sensors include timestamps, then I suppose the application will want to use that. If the sensors do not include timestamps, then adding timestamps at ingestion is possibly an acceptable approximation. One option in addition to the one proposed above for ingestion time is to produce a timestamp and embed it into the event before writing to the Pravega stream.

If the event has an embedded timestamp, then an important question is whether the connector is able to extract the timestamp for the purposes of generating watermarks. If it can, then is that not a suitable solution? One weak point with this option is idleness as there is nothing indicating that a reader (source) is idle.

**Comment by EronWright** [comment]
It is true today that Flink applications extract the timestamp from the record body, for most data sources.   Those apps then use the timestamp to infer a watermark based on a heuristic, for example: "I just observed a record with timestamp of 11:00.  Assuming a bounded out-of-orderness, I may infer a watermark of 10:55."   Such an inference is reasonable only if the order of observation is closely related to the event time, which is not the case in Pravega even with PDP-28.
