### ISSUE TITLE
Pravega security: `listScopes` should do authorization checks too

### ISSUE THREAD

**Issue by arvindkandhare** [pravega/pravega#2391]
**Problem description**
Current implementation of `listScopes` does authorize or authenticate. This should follow the usual
procedure where we authorize the user for each stream and just show the stream that he has access to.

**Problem location**
`listScopes` implementation here:
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/rest/resources/StreamMetadataResourceImpl.java#L469

**Suggestions for an improvement**
This should follow the usual
procedure where we authorize the user for each stream and just show the stream that he has access to.

**Comment by EronWright** [comment]
Depending on the handler, this may cause N remote calls to the authorization server (where N is the number of scopes or streams).   A possible mitigation would be to provide an authorization context object into calls to `authenticate` and `authorize`, such that some context data could be stored across repeated calls.

**Comment by sarlaccpit** [comment]
Yes it could be a problem. It’s almost like we’d need another acl semantic to represent the list operations.   Just thinking out loud, For example, list scopes would lead to a call to authorize(“/“, “LIST”).   The result of that would not be a Permission, but rather a filtered list of the resources at the provided level.  In this case “/“ is top level, so filtered list of scopes is what would come back. 

That would require another kind of “authorize” in the interface. I’m not sure what the right name would be. But it would encompass these ideas: “peek”, “filteredListOf”, “authorizedListOf”.   

`List<String> authorizedListOf(String resourceType, Map<String, String>authParams)`is what I’m thinking of.

**Comment by EronWright** [comment]
@sarlaccpit a compromise would be a batch-style authorize method: 
```
public Permissions[] authorize(String[] resources, Map<String, String> authParams)
```

Yet another solution is to retain some state across repeated calls.   For example, the handler could return a prinicpal object to retain some internal state (i.e. some retrieved role info) to be used in subsequent calls, or even mutated across calls.
```
public PravegaPrincipal authenticate(Map<String, String> authParams);

public Permissions authorize(String resource, PravegaPrincipal principal);
```
A principal object would solve other problems, such as conveying a username to Pravega for logging purposes.

**Comment by EronWright** [comment]
Please give my latter suggestion some consideration because it will pay dividends to facilitate the use of state across authentication and authorization stages.   It is utterly typical to have such functionality in authentication frameworks.

**Comment by arvindkandhare** [comment]
> Please give my latter suggestion some consideration because it will pay dividends to facilitate the use of state across authentication and authorization stages. It is utterly typical to have such functionality in authentication frameworks.

@EronWright I spent some time thinking about this. Here is what I think: the ability to cache the state should be left to the plugin implementation based on specific framework it is using. 
Pravega controller/client, being transparent to the plugin implementation, does not have any clue about how auth works and how to cache the creds and manage state.

It will be helpful if you could point to some pluggable auth implementations which have this functionality for reference.

Otherwise it makes sense to add another access level as @sarlaccpit suggests. Adding another level `LIST` which is lower than `READ` in `AuthHandler.Permissions` makes sense.

**Comment by sarlaccpit** [comment]
Wrt caching the state between authenticate() and authorize(), I think it's natural to think of it here because depending how we implement _this_ particular change of filtering scopes, it could impact performance very negatively.

But, I think it does remain a separate issue and for this current filtering problem, what makes most sense to me is to have the batching type call Eron is suggesting, which can postpone the issue of state/caching to later.  The flow would be like this:

`listScopes()` would call a new 
`String resources[] authenticate(String resources[], AuthHandler.Permissions level)`
which simply an overload of `authenticate(String resource, AuthHandler.Permissions level)`

and the plugin implementation is responsible for returning a filtered down list of what was passed to it (presumably the whole list of scopes in this case).  

(it may be argued that instead of an overload of `authenticate`, it could be called something else like `filteredAsAuthorizedList()` or similar, since it's technically a bit different; this call doesn't return a permission like `authenticate()` does, it returns a list of resource names)

Also, I don't think we necessarily need a new `LIST` permission.  Seems like READ would be good enough? (I don't have a preference).   It would seem simple to me: if you have at least READ on a scope, you get to see if in the list of scopes that's returned to you.

I think the issue of caching/state gets avoided here because it's up to the plugin to intelligently compute the filtered list based on the token it was given.
