### ISSUE TITLE
ReadTest failure

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2409]
**Problem description**

Test failure on Travis:

```
io.pravega.test.integration.ReadTest > testReceivingReadCall FAILED
    java.lang.AssertionError: expected:<java.nio.HeapByteBuffer[pos=0 lim=100 cap=100]> but was:<java.nio.HeapByteBuffer[pos=0 lim=90 cap=90]>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.pravega.test.integration.ReadTest.testReceivingReadCall(ReadTest.java:149)
```

**Problem location**
Integration test.

**Suggestions for an improvement**
Track the test failure.

**Comment by shrids** [comment]
Initial investigations reveal that `StreamSegmentReadIndex#getMultiReadResultEntry()` method reads just 90 bytes insteadof the expected 100. This causes the reponse `io.pravega.shared.protocol.netty.WireCommands.SegmentRead` to return with 90 bytes instead of the expected 100.

Detailed Logs: 
[testFailureLog.log](https://github.com/pravega/pravega/files/1859519/testFailureLog.log)

```
	Line 25: 2018-03-29 09:41:44,150 INFO  [main] reading.StreamSegmentReadIndex (StreamSegmentReadIndex.java:getMultiReadResultEntry(781)) - ==> io.pravega.segmentstore.server.reading.StreamSegmentReadIndex.getMultiReadResultEntry readLenght:90 
	Line 26: 2018-03-29 09:41:44,151 INFO  [main] handler.PravegaRequestProcessor (PravegaRequestProcessor.java:collectCachedEntries(266)) - ==> CollectCachedEntries = entry CacheReadResultEntry: Offset = 0, RequestedLength = 90, HasData = true, Error = false, Cancelled = false, expectedOffset = 90, content.getLength = 90
	Line 27: 2018-03-29 09:41:44,151 INFO  [main] handler.PravegaRequestProcessor (PravegaRequestProcessor.java:collectCachedEntries(270)) - ==> CollectCachedEntries Before return = entry : FutureReadResultEntry: Offset = 90, RequestedLength = 9910, HasData = false, Error = false, Cancelled = false, readResult: Offset = 0, MaxLength = 10000, Consumed = 90
	Line 28: 2018-03-29 09:41:44,151 INFO  [main] handler.PravegaRequestProcessor (PravegaRequestProcessor.java:handleReadResult(220)) - ==> handleReadResult=  data after copyData data.remaining:90

```

**Comment by tkaitchuck** [comment]
Per the StreamSegmentStore.read contract this is acceptable. Why is it causing problems?

**Comment by andreipaduroiu** [comment]
The test is not expecting a Future read result entry. This may happen because the ack came back to the client faster than the store was able to store the data in the cache. This only happens because we do this test in process so we have a 0ms latency between client and server. In a real world scenario where we have a non-zero latency, this is less likely to happen, but the Client does handle future reads properly.

I'll submit a PR to fix these two tests.
