### ISSUE TITLE
Support jCasbin as the authorization backend

### ISSUE THREAD

**Issue by veotax** [pravega/pravega#2485]
[jCasbin](https://github.com/casbin/jcasbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.
4. multiple models like ACL, BLP, RBAC, ABAC, RESTful are supported.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I saw this issue: https://github.com/pravega/pravega/issues/1669 said there's a plan to build the RESTful authorization, and I think jCasbin can be a choice. What do you think? Thanks.

**Comment by EronWright** [comment]
jCasbin appears to be a library for making an authorization decision, that would be loaded as a plugin into the Pravega controller.  Upon a resource request, after authentication has occurred (i.e. we've established who the caller is), jCasbin would consult a database of policies to make an authorization decision.

Some of the challenges I see:
1. Pravega doesn't provide data storage for its auth plugins, so the ability to dynamically adjust policies (if needed) would depend on some external storage.
2. A fix for #2396 would be needed to load a static jcasbin policy file.
3. Since jcasbin doesn't handle authentication, the plugin would need to invent something.   Perhaps use a password file (like the 'default' plugin does).
