### ISSUE TITLE
Enable textual representation of a StreamCut.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega#2490]
**Problem description**
Enable a textual representation of a StreamCut which can also be used to reconstruct the object.
This textual representation can be used as a command line parameter while starting the connector job.

E.g:
` flink run MyJob --input scope1/stream1 --from <cut-data>`

**Problem location**
StreamCut.

**Suggestions for an improvement**
At present `StreamCut` supports `java.io.Serializable` java serialization;  Ensure we have a textual representation of it

**Comment by EronWright** [comment]
Let's clarify what we mean by 'textual representation'.   Primarily I take it to mean a string that may be easily passed as a program parameter, pasted into a text box, etc.   I think it unimportant for the value to be transparent (easily interpretable and/or editable by humans).    For example, a good value might be `scope1/stream1:MT0xOzI9MzQ1MzI7Mz00NTYzOzQ9NDU3NjM1` (i.e. a base64 value containing segment offsets, in a compressed or otherwise efficient format).

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Textual representation of stream cuts.](https://trello.com/c/DV4TGNM1/23-textual-representation-of-stream-cuts)

**Comment by shrids** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Textual representation of stream cuts.](https://trello.com/c/DV4TGNM1/23-textual-representation-of-stream-cuts)
