### ISSUE TITLE
Events read out of sequence

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#2628]
**Problem description**
Within our "midScale" longevity test, we keep track of the sequence number for the events written to a stream. Then there is an assertion that the readers should be reading the events in the incrementing order.
After running our test for two days an writing/reading 1,000,00 events we observed two events read out of order: 
```
2018-05-23 18:58:51,902 166637424 [pool-8-thread-8] ERROR c.e.n.h.t.w.readers.PravegaReader - Event out of sequence 088c6e3a-3a3f-4a50-bfcc-a41e301182a7-33c1982a-12ad-4690-af68-8dfe3e38c672: lastSeq: 1003587, currentSeq:1003586
```
There are four clients writing to the stream at the same time (four writers and eight readers per client, one reader group and one writer group total).
The event payload is identified with the writer ID, this means we observed the events written by *the same writer* being read out of sequence. 

Attached is the client log at DEBUG level:
[reads_out_of_sequence.controller_server_2018-05-23.5574.log](https://github.com/pravega/pravega/files/2040630/an_out_of_sequence.tan.midScale.controller_server_2018-05-23.5574.log)

**Problem location**
Client

**Suggestions for an improvement**
The events should be read in the same order as they are written.

**Comment by tkaitchuck** [comment]
I think I have an explanation as to what is happening:
In EventStreamWriterImpl it has the function handleLogSealed() this replaces the old segment with the new one can calls flush() on each of the current segments. 
The reason that flush() is call is so that all the writes that are going to be written to any sealed segments are written and the seal is encountered. This way before the lock is released the seal is queued up in the sealedSegmentQueue and it can be processed. This is because we want to prevent the possibility that a write comes in between the adding of the replacement segment and the transmission of the events from the old segment to the new segment.
However looking at the code to SegmentOutputStreamImpl, it actually unblocks the flush before the seal is in the sealedSegmentQueue. So there is a race where an event could arrive after the release of the lock.
