### ISSUE TITLE
Incomplete verification in ReaderGroupConfig.verifyStartAndEndStreamCuts()

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#2668]
**Problem description**
When start and end stream cuts are passed to reader group, it verifies that the end cut's highest segment is below the begin cut's and the reverse for the lowest segment. However this is not sufficient to catch all invalid pairs of stream cuts. It could be possible for streamcuts to be overlapping and not ordered with respect to one another, but still have the highest and lowest segments be consistent. 

**Problem location**
ReaderGroupConfig.verifyStartAndEndStreamCuts()

**Suggestions for an improvement**
More thoroughly verify that the ranges are consistent. 
This could be generalized by having streamCuts implement comparable.

**Comment by huide9** [comment]
Based many rounds discussion on slack with Shivesh, Tom, Sandeep, the tasks for the issue is defined as below: (I'm going to go ahead for the implementation, please comment for any further thinking)

• goal: to provide a function for verifying: if the given `startStreamCut` and `endStreamCut` is valid at the client start phase
• solution: merge the keyspace and segment verification (which implemented in `RecordHelper.validateStreamCut` and `RecordHelper.streamCutComparator`) ,  generate a new API which can call into both those methods; so it will only need one time calling; 
   The following steps might be needed: (please suggest for any steps wrong or insufficient)
   1. controller side: combine the 2 validation functions into a new method: `RecordHelper.verifyStartAndEndStreamcuts()` in `RecordHelper`
   2. adding new API in: Controller.proto -  combined API:  verifyStartAndEndStreamcuts
   3. modify `ControllerService` and `ControllerServiceImpl`  to add the related API
   4. provide the method for verifyStreamCuts at the proper location - which will call the API  (support to be a common class i.e., `ClientFactoryImpl`
• test cases.

**Comment by shiveshr** [comment]
>  1 combine the 2 validation functions into a new method: RecordHelper.isStartAndEndStreamcutsValid() in RecordHelper

Why do you want to combine these two methods?

Here is what you should do:
1. add new api in Controller.java (on client) for validation of start and end stream cuts
2. add new grpc api for validation of start and end stream cuts
3. ControllerImpl.java will have client side grpc implementation
4. ControllerServiceImpl.java will have service side grpc implementation
5. add new method in StreamMetadataStore
5.1 Add method in Stream interface
5.2 in Stream implementation (PersistentStreamBase) implement your business logic. Use RecordHelper as the helper class where you can write some helper routines for performing computations on records. 
5.3 You can write a wrapper method on the two methods you mention in RecordHelper instead of combining the two into a single method.

**Comment by huide9** [comment]
consider this validation is at the beginning phase of the client, so the performance concern (grpc calling) shouldn't be a problem.

**Comment by huide9** [comment]
the reason to "combine" (wrap is a better word actually) the two methods is: one of the method is to verify the key space (`full key space`) and  `key space overlap`, the other method verified `segment order no overlap` btw two stream cuts.  this 3 validation should be sufficient to verify if the stream cuts valid or not and also covered Tom's concern here.

**Comment by shiveshr** [comment]
There is another important factor to consider before introducing any such api with using the existing validation methods on controller. 
These methods assume stream cuts to cover entire key space with zero overlaps. 
However, that definition of a stream cut has problems and stream cuts generated by readergroups could contain only a partial range of keyspace. 
Note: those streamcuts are ambiguous, but unless we change the representation of streamcut to capture additional details to rid of ambiguity, the current validation will reject streamcuts that applications get from readergroups. 
So my suggestion is that we first fix the stream cut representation and then update the validation logic on controller accordingly. 
Then we can have all sorts of apis to validate different stream cuts and compare them if needed.
