### ISSUE TITLE
Improve output upon timeout of system test cases

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#2688]
**Problem description**
The current system test cases often time out on the general test case timer. It would be more useful if upon timing out we had concrete information as of why the test timed out. For example, if the test case failed because a reader failed to complete its task, then we would rather know that it was because of a reader rather than getting a generic test case time out.

**Problem location**
System tests.

**Suggestions for an improvement**
One concrete suggestion would be to use `Futures.await` with a timeout across the test cases that we have rather than wait indefinitely.

**Comment by andreipaduroiu** [comment]
This is a great idea. But what I am really after is not really letting the test time out at all. If we get that far, we must have missed something important - unless the timeout is really due to some real slowdown.

What I would like to see improved is a better assertion coverage. I would like that the system tests check the state of the system in greater detail and fail the test as soon as some anomaly is found. Having something like this would greatly reduce the amount of time we need to spend plowing through logs and trying to see why a test timed out.

This can be as simple as putting a timeout every time we wait on a Future, so we at least know what's waiting, to doing more asserts (we are expecting things to be like this at the moment, however they are not; this is probably something bad).
