### ISSUE TITLE
Remote app cannot connect to standalone Pravega node

### ISSUE THREAD

**Issue by bfrggit** [pravega/pravega#2837]
**Problem description**
VM_1 runs the standalone Pravega node as is instructed by: http://pravega.io/docs/latest/deployment/run-local/. Port 9090 is open on its firewall.
Remote simple writer running on VM_2 uses controller URI "VM_1_IP:9090", but it reports "connection refused" on "127.0.0.1:6000". Obviously, VM_2 does not have anything listening on 6000.

**Problem location**
Standalone mode or its configuration.

**Suggestions for an improvement**
Fix it?

**Comment by RaulGracia** [comment]
Hi @bfrggit, thanks for your feedback.
It looks that the `SegmentStore` process is being registered in the cluster with the loopback address instead of with a reachable local address in your network. This is probably because the `standalone` mode is mainly assumed to run in a single node. If you want to run Pravega in multiple nodes (or VMs), I recommend you to try the Docker Compose mode and then you will be able to set the appropriate `HOST_IP`.

**Comment by ravisharda** [comment]
I faced the same issue today with: 
- Reader/writer clients applications running on my local host. 
- Standalone Pravega node ran from source on a remote VM. 

A message "_Connection refused: no further information: /127.0.1.1:6000_" was present somewhere in the client logs. The workaround was to move the client application to the remote VM.

**Comment by RaulGracia** [comment]
An even simpler way of executing Pravega in multiple nodes is just to start a Zookeeper instance in one of the nodes, and download the release artifacts of Pravega in the desired nodes. Then, just update the `config.properties` file in the nodes to point to the Zookeeper instance and execute `pravega-controller` and/or `pravega-segmentstore` in the nodes as desired. Then, make sure that the sample/client application does not point to a `localhost` controller (by default); you just need to update the `-uri` option with the Controller location as described [here](https://github.com/pravega/pravega-samples/tree/master/pravega-client-examples).
