### ISSUE TITLE
Pravega client lacks API to write events in sequence

### ISSUE THREAD

**Issue by kevinhan88** [pravega/pravega#3119]
**Problem description**
Currently in order to keep sequence of events with different keys, client can only create a stream with one fixed segment. There is no parallelism possible for this option.
An API is needed for client to write any event to a specified stream, in order to keep the order of events. 
If this API is available, then application can create stream with multiple segments, and write event to a particular segment per the order defined by application, in order to keep the sequence of all the events in a Pravega stream.

**Problem location**
client/src/main/java/io/pravega/client/stream/EventStreamWriter.java
client/src/main/java/io/pravega/client/stream/impl/EventStreamWriterImpl.java
client/src/main/java/io/pravega/client/stream/impl/SegmentSelector.java
client/src/main/java/io/pravega/client/stream/impl/StreamSegments.java
...

**Suggestions for an improvement**
Add method write(int segmentId, String event) into EventStreamWriter interface

**Comment by fpj** [comment]
Thanks for reporting this issue, @kevinhan88 . The description of this issue is not making a lot of sense to me. First, why would you want global order of writes? With multiple parallel segments, even if you guarantee that the events are written in order, by say writing one at a time and waiting for the acknowledgement, there is no guarantee that they will be read in that same order.

Also, we do not expose the segment abstraction as of today as we don't want to complicate the application with the logic to handle the dynamics of streams mainly due to scaling. This is not a missing a feature, but instead a conscious design choice. If you are having an issue with order, then I suggest you describe your issue here and we can see what the best way of addressing it is, but the change you are proposing here isn't a lightweight one.

**Comment by kevinhan88** [comment]
Close the issue for now after the conversations with the team. 
For now, the approach to keep record order is to create multiple streams, each with fixed(1) segment.
