### ISSUE TITLE
Revisit authorization logic

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3277]
**Problem description**
1. The authorization subsystem doesn't give adequate information to the authorization handler, to disambiguate between scope creation and scope use.   One is unable to grant to the administrator the ability to create scopes, and grant to a user the ability to create streams within a given scope (but not to create scopes).   Similar situation for scope deletion.

2. Similar situation for streams with respect to scopes; e.g. the ability to write to a stream without the ability to create streams.

3. Some of the calls are marked as requiring `READ_UPDATE` whereas `READ` may be sufficient:
- `getCurrentSegments`
- `getSegments`
- `getURI`
- `isStreamCutValid`
- `getDelegationToken`  (varies by situation?)

**Problem location**
- `io.pravega.controller.server.rpc.grpc.v1.ControllerServiceImpl`
- `io.pravega.controller.server.rest.resources.StreamMetadataResourceImpl`

**Suggestions for an improvement**
Adjust the argument passed to the `authorize` call on the auth handler, such that a call to create or delete a sub-resource has the parent resource as the argument.   For example:

|action|logic|
|-----------|-----------------------|
|list scopes | `authorize("/", READ)` |
|create scope | `authorize("/", READ_UPDATE)` |
|delete scope | `authorize("/", READ_UPDATE)` |
|list streams | `authorize(scopeName, READ)` |
|create stream | `authorize(scopeName, READ_UPDATE)` |
|delete stream | `authorize(scopeName, READ_UPDATE)` |
|read stream | `authorize(scopeName + "/" + streamName, READ)` |
|write stream | `authorize(scopeName + "/" + streamName, READ_UPDATE)` |

Be sure to update `ControllerServiceImpl` and `StreamMetadataResourceImpl` since the logic is duplicated.

**Comment by sarlaccpit** [comment]
I think the table captures a state of things that makes sense to me.

One nuance that is missing from the list though is the desire to be able to list all scopes on one hand, but also filtered by what the user has access to on the other hand.

In other words, if a user has READ on 3 out of the 10 scopes available, list scopes should return those 3.   Additionally, it would be best if that didn't require the user to have READ on /, since this is what the list all scopes requires.

Perhaps what we need is 2 calls.

- An admin call:  "list all scopes" (/v1/scopes)  --> requires READ on /.  You have it, you see everything, you don't have it, you see nothing.
- a user call: "list my scopes" (/v1/myscopes) --> does not require READ on /.  Will retrieve all scopes that the user has READ on and return that list.

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Need to Add Ravi's Card](https://trello.com/c/BlxeDUJY/86-need-to-add-ravis-card)

**Comment by ravisharda** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [3277 - Revisit authorization logic](https://trello.com/c/TbQ1aPTA/1-3277-revisit-authorization-logic)

**Comment by ravisharda** [comment]
@EronWright and @sarlaccpit FYI, I've started working on this issue.

**Comment by EronWright** [comment]
@sarlaccpit would the following be a solution to the above issue:  
- treat `authorize("/", READ)` as a low-privilege operation (everyone has it)
- within the controller, filter the results to those scopes that the user has access to.  e.g. by calling `authorize(scopeName, READ)` in a loop.

Assuming the admin has access to all scopes (due to an appropriate keycloak policy), the net effect would be as you describe.  WDYT?

**Comment by sarlaccpit** [comment]
@EronWright I agree.  This would solve the listscopes issue.

**Comment by ravisharda** [comment]
@EronWrigt and @sarlaccpit 

Below are some thoughts and clarifying questions. 

It seems like there are two different types of authorizations we are talking about here: 
1. The first type that answers "is the caller authorized to perform the operation it is invoking?"
2. The second type that filters records (e.g., scopes, streams, etc.) based on the ones the caller has access to. 

I suppose both of these authorizations are handled by auth handler implementations. Please correct me if I'm wrong. 

The table listed in the description applies to (1) above. I was thinking it might make sense to have a consistent scheme for identifying a resource, so that handler implementations can use the parts that make sense to them. Something like:  ``//scopeName:streamName/eventId``

If we did this, the resource argument passed to authorize method of the handler'd then become as shown in the table below: 

| Operation | Logic |
|:------|:--------|
| List scopes | ``authorize("//", ...)`` |
| Create scope |  ``authorize("//", ...)`` |
| Delete a scope | ``authorize("//scopeName", ...)``  |
| List streams | ``authorize("//scopeName:/", ...)``  |
| Create a stream | ``authorize("//scopeName:/", ...)`` |
| Delete a stream | ``authorize("//scopeName:streamName/", ...)`` |
| Read a stream | ``authorize("//scopeName:streamName/", ...)`` |
| Write to a stream | ``authorize("//scopeName:streamName/", ...)`` |

Is the above scheme workable? 

Question about (2) above: 

Are the access rules for (2) statically defined? For example: 
* Admins have read/write permissions to all scopes. 
* User1 has access to scope1 and scope2, and stream1 in those scopes. 
* and so on...

Or, are the access rules for (2) more dynamic? Say, based on some sort of "ownership model" like if I create a scope, I have read/write access to it. How does the auth handler find out "who owns what"?

**Comment by ravisharda** [comment]
@EronWright I have another question. Shouldn't delete operations (delete scope and delete stream) also have the resource name (scope name and stream name respectively) apart from the parent resource name in the resource string? 
* Delete scope: "/scopeName"
* Delete stream: "scopeName/streamName"

For example, a user might have access to delete streams of a given scope in general but might not own a  particular stream and might need to be prevented from deleting that stream, warranting something like "scopeName/streamName" as the resource name. 

What do you say?

**Comment by EronWright** [comment]
@ravisharda I say that is incorrect because, as the description makes clear, we have only two scopes to work with - read and read_update.   It is thus impossible to distinguish between an ability to create a scope (which we consider to be high-privilege) and to create streams within that scope.

**Comment by ravisharda** [comment]
@EronWright and @sarlaccpit I had to temporarily halt the work on this in favor of another pressing issue. I'm expecting to get back to this soon (this week, hopefully). 

In the meantime, I was thinking it might be a good idea to get some early feedback on the changes I've made (but not fully tested yet). Do you mind reviewing my changes directly on my fork to see if they meet your requirements? They can be found in [this branch](https://github.com/ravisharda/pravega/tree/issue-3227-auth-logic)  of my fork.

**Comment by ravisharda** [comment]
The table below shows the resource strings and permissions required as of [PR 3386](https://github.com/pravega/pravega/pull/3386), which includes changes based on the asks made in this issue. (There were a few that had to be left out, like lowering of permission required for ``getCurrentSegments`` from ``READ_UPDATE`` to ``READ``, which made sense conceptually but there were resulting issues found upon testing). 

There are a few inconsistencies in the authorization model that we'll need to address, which are explained below. Also presented are a couple of options to solve them. 

|S.No.| Action |	Resource String for Auth (in this PR)  | Required Permission | gRPC method (in ``ControllerServiceImpl``) | REST controller method (in ``StreamMetadataResourceImpl``| 
|:--:|:-----------|:---------------:|:---------------:|:---------------:|:----------------------|
|1.| List scopes |  ``/``, and <br/>``<scope-name>`` for each scope|READ |-|``listScopes``| 
|2.| Get a scope |  ``<scope-name>`` |READ |-|``getScope``| 
|3.| Create a scope | ``/`` |READ_UPDATE |``createScope``|``createScope``| 
|4.| Delete a scope | ``/`` |READ_UPDATE |``deleteScope``|``deleteScope``| 
|5.| List streams | ``<scope-name>`` |READ |-|``listStreams``| 
|6.| Get a stream | ``<scope-name>/<stream-name>`` |READ |-|``getStream`` |
|7.| Create a stream |  ``<scope-name>`` |READ_UPDATE |``createStream``|``createStream``| 
|8.| Update a stream |  ``<scope-name>/<stream-name>`` |READ_UPDATE |``updateStream``|``updateStream``| 
|9.| Update a stream's state |  ``<scope-name>/<stream-name>`` |READ_UPDATE |-|``updateStream``| 
|10.| Delete a stream |  ``<scope-name>`` |READ_UPDATE |``deleteStream``|``deleteStream``| 
|11.| Truncate a stream |  ``<scope-name>/<stream-name>`` |READ_UPDATE |``truncateStream``|-| 
|12.| Seal a stream |  ``<scope-name>/<stream-name>`` |READ_UPDATE |``sealStream``|-| 
|13.| List reader groups | ``<scope-name>`` |READ |-|``listReaderGroups``| 
|14.| Get a reader group |  ``<scope-name>/<reader-group-name>`` |READ |-|``getReaderGroup``| 
|15.| List scaling events of a stream |  ``<scope-name>/<stream-name>`` |READ |-|``getScalingEvents``| 
|16.| List current stream segments | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``getCurrentSegments`` | -|
|17.| List stream segments | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``getCurrentSegments`` | -|
|18. | List segments following| ``<scope-name>/<stream-name>``| READ | ``getSegmentsImmediatlyFollowing``|-|
|19.| List segments between | ``<scope-name>/<stream-name>``| READ | ``getSegmentsBetween``|-|
|20.| Scale (a stream) | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``scale``|-|
|21.| Check scale status | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``checkScale``|-|
|22.| Get URI for segment | ``<scope-name>/<stream-name>`` | READ | ``getURI``|-|
|23.| Is Segment valid | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``isSegmentValid``|-|
|24.| Is stream cut valid | ``<scope-name>/<stream-name>`` | READ | ``isSegmentValid``|-|
|25.| Create a transaction | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``createTransaction``|-|
|26.| Commit transaction | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``commitTransaction``|-|
|27.| Abort transaction | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``abortTransaction``|-|
|28.| Ping transaction | ``<scope-name>/<stream-name>`` | READ | ``pingTransaction``|-|
|29.| Check transaction state | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``checkTransactionState``|-|  
|30.| Get delegation token | ``<scope-name>/<stream-name>`` | READ_UPDATE | ``getDelegationToken``|-|  

Some of the inconsistencies in the authorization model, are as follows: 

* Updating a stream requires ``READ_UPDATE`` on the resource ``<scope-name>/<stream-name>``. But, deleting a stream requires ``READ_UPDATE`` on merely the parent resource ``<scope-name>``. 
* While listing scopes (1), apart from checking that the user is authorized to list scopes (based on ``READ`` on parent resource ``/``), we now also filter the output to show only authorized scopes (based on ``READ`` on resource ``<scope-name>``). However, we let the user delete any scope, as long as she has ``READ_UPDATE`` on parent resource ``/``). Also, if the admin provides a user ``READ`` on ``myscope1`` to allow her to view that scope, the user also automatically gets an ability to list streams. 
* There are also inconsistencies between different operations on the same resource. For example, Delete stream requires ``READ_UPDATE`` on parent resource ``<scope-name?``, truncate stream requires ``READ_UPDATE`` on the resource ``<scope-name>/<stream-name>``. 

I think we'll need to make the resource strings consistent. A couple of alternative options for achieving that show in the table below.

|S.No.|  Title | In the current model (as of PR) | Alternative 1: <br/>"Coarse-Grained" Approach | Alternative 2: <br/>"Fine-grained" Approach |
|:---:|:-----------|:----------------------------|:------------------------|:-----------------------|
|1.| Resource string definition | - Upto resource in some cases. For example: Update a stream: ``<scope-name>/<stream-name>``, and<br/> - Upto parent resource in other cases (Delete a scope: ``<scope-name>``) | Always upto ``parent`` | - Upto parent resource for listing and create operations (e.g., Listing scopes: ``/`` creating a scope: ``/``), <br/> - Lists are filtered based on accessible objects (e.g., ``scope-name`` while listing scopes or ``scope-name/stream-name`` while listing streams), <br/> - Upto resource for update/delete operations for scopes and streams (e.g., Delete a scope: ``scope-name``, Update/delete a stream: ``scope-name/stream-name``) | 
|2. | Implications | - | Authorizations apply at "operation-level". For example, if a user has access to delete a scope (``/``), she can delete any scope. Similarly, if a user has access to fetch a stream (``<scope-name>``), she can fetch any streams in that scope. On listing scopes or streams, a user sees all scopes and streams (of a given scope).| Authorizations apply both at "operation" and "object/instance" (for lack of a better term) level. For example: A user might have access to delete a given scope, but not another one. On listing scopes or streams, a user sees only scopes and streams that he has access to.| 
|3.| Pros and Cons | Authorization model is inconsistent. | Authorization model is less powerful than option 2, but consistent and simple-to-use.  | Authorization model is more difficult to use, but is consistent and powerful.| 

@fpj and @EronWright - I want to open up some discusson about how to get going on this. Please share your thoughts/comments.

**Comment by EronWright** [comment]
I’m worried that the whole scenario of having read-only access to a stream is broken, due to ‘READ_UPDATE’ being required for 16, 17, 23, 30.

**Comment by fpj** [comment]
@ravisharda I'm in general interested in having a consistent model, and as such, I don't mind choosing one option over the other. I find that option 2 gives more control to the user over the stream resources, though, so I have a slight preference for that option. You say that it is harder to use, but I'm not sure what you are referring to.

I think there are some other inconsistencies in your table that you haven't mentioned:
1- The following operations require `READ_UPDATE`, but they are really about reading the state of the resource:
   -  List current stream segments (16)
   - List stream segments (17)
   - Check scale status (21)
   - Is segment valid (23)
   - Check transaction state (29)
   - Get delegation token (30)

Cases 21 and 29 are arguable because they are part of operations that change the state of streams, but they are not changing the status of anything. About 30, I don't understand why it needs to be `READ_UPDATE`.

2- About case 28: Ping transaction. Pinging a transaction actually changes the state of the transaction, so I think it should be `READ_UPDATE`.

**Comment by ravisharda** [comment]
@fpj , @EronWright 

To answer your questions about other inconsistencies: 

For this issue and the corresponding PR [3386](https://github.com/pravega/pravega/pull/3386), I've only addressed the very specific issues mentioned in the description of this issue and the PR, which primarily concern the scopes and streams. Doing so lets us address the scenario mentioned under the sub-section "Problem 1" in the PR description field and the issues described in items 1 and 2 in the description field of this issue. 

With respect to operations that currently require READ_UPDATE but ideally should require READ,  I've addresses only two of them as mentioned in the description field of the PR [3386](https://github.com/pravega/pravega/pull/3386). All of the inconsistencies mentioned in your comments are from earlier: 16, 17, 21, 23, 28, 29, 30, and I think they should be addressed as part of another issue - just to avoid making the scope of this issue/PR enormous. I did try to make some of the operations like list current segments (16) require READ permission, but then noticed the functionality breaking. 

Also, 
> @fpj : You say that it is harder to use, but I'm not sure what you are referring to.

What I meant is it'll be slightly harder to define authorization rules and making sense of their runtime behavior.

As for me, I'm in favor of option 2, as well. I shall be going ahead with implementing it, unless I hear objections.

**Comment by fpj** [comment]
@ravisharda Let's try to organize what needs to happen out of this conversation:

1- I really like your table summarizing the authorization model. It enabled us to spot the inconsistencies we have added to the thread. One action item is to fix those inconsistencies at the operation level.
2- The other action item is to decide on which approach to follow from the ones you have suggested to fix the inconsistencies on the rights that permissions are giving across resources.

I'm fine with going with the fine-grained approach above, but again, my primary goal is to have a consistent model. As for how to execute it, I'm assuming you don't want to do everything in a single PR. If that's right, and makes sense, we can use this issue as an umbrella issue and create a checklist in the description with the corresponding. What do you think?

**Comment by ravisharda** [comment]
@fpj sounds great to me. I'll use this as an umbrella issue, address no. 2 (from your last comment) in PR [3386](https://github.com/pravega/pravega/pull/3386), and address no. 1 separately in different PR. 
Thanks!

**Comment by sarlaccpit** [comment]
A problem with option 2, and the idea of having list/create looking at the parent resource, but delete/update at the actual resource is it creates an asymmetry that's a bit confusing, but mostly create legitimate problems:

For example, I'm a top level admin, I have READ_UPDATE on /, I create a scope.   I give READ_UPDATE to chris on that scope.    chris can now create streams in that scope, but he can also delete that scope that the admin created.

I think the problem is that READ_UPDATE encompasses write/delete/create and thus cannot adequately represent the various scenarios.

Option 1 is indeed more broad ( create / delete scope at the same level, require READ_UPDATE on /.  Only admin has that.  chris in this example has READ_UPDATE on the scope he was given and can only create things _below_ it.)

Option 2 is more powerful but as I view it (unless I missed some nuances), doesn't work because of the problem above.

I think we need to either:

- do option 1
or
- introduce CREATE, DELETE, WRITE, READ separate permissions on things.

**Comment by sarlaccpit** [comment]
just adding to my last comment.   I guess option 2 can work if we say that READ_UPDATE is basically also like transferring ownership of the object...

As in:  The admin creates the scope X (by means of its READ_UPDATE on /) and gives READ_UPDATE on X to chris.  By doing so, the admin is transferring full ownership (or sharing) of X to chris.   chris can do anything to and below that scope, INCLUDING destroying it.

I think it works if that is the intent.

**Comment by fpj** [comment]
@sarlaccpit

> I'm a top level admin, I have READ_UPDATE on /, I create a scope. I give READ_UPDATE to chris on that scope. chris can now create streams in that scope, but he can also delete that scope that the admin created.

I agree that option 2 has this limitation, but option 1 also has issues, like anyone with update access on a scope being able to delete any stream in the scope.

Clearly sticking to only `READ` and `READ_UPDATE` only won't enable us to  clear all these scenarios. I agree that the way forward should be to have fine-grained rights organized as a different set of permissions.

As I said above, I don't have a super strong preference between options 1 and 2, but I have a slight preference for option 2 assuming we are sticking to `READ` and `READ_UPDATE` short term.

**Comment by EronWright** [comment]
I think this is partly completed.  Maybe we should update the title or file successors.

**Comment by ravisharda** [comment]
> I think this is partly completed. Maybe we should update the title or file successors.

Thanks @EronWright. 

Pull requests [3386](https://github.com/pravega/pravega/pull/3386) and [3492](https://github.com/pravega/pravega/pull/3492), which resolved issues [3410](https://github.com/pravega/pravega/issues/3410) and [3411](https://github.com/pravega/pravega/issues/3411) respectively, addressed most of what was discussed in this issue. For the pending items, I've now filed the following successor issues: 
1. Reducing permission required for Controller gRPC read operations (#3872).
2. Granular permission model (#3879).
