### ISSUE TITLE
Add listStreams() method to the gRPC client

### ISSUE THREAD

**Issue by bourgeoisor** [pravega/pravega#3278]
**Problem description**

The current implementation of the StreamManager for Java allows users to manage scopes and streams, but is missing an important method: listing streams. This is particularly useful when wanting to delete a scope that contains streams (this fails and streams need to be manually purged). There is a `.deleteStream()` method in the implementation but no methods to actually list out the current streams.

This is available to the REST API, but not to the Java gRPC-enabled client.

**Problem location**

`io.pravega.client.admin.impl.StreamManagerImpl`

**Suggestions for an improvement**

Add the following method to the implementation of the StreamManager for the Java client:

`streamManager.listStreams()`

**Comment by shiveshr** [comment]
Since we have createScope and deleteScope available in grpc, so i dont see any reason why we should not have listStreamsInScope in grpc. 
I will add the grpc. @tkaitchuck @shrids IMO this api also ought to be exposed on StreamManager interface and i can make that change as well unless there is any objection to it.

**Comment by shiveshr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [List Streams in scope with pagination](https://trello.com/c/XBbsA0Hn/99-list-streams-in-scope-with-pagination)
