### ISSUE TITLE
One particular Segment which is less than the scaling trigger (events/sec) all the time, doesn't get merged with neighbors during the entire longevity run on Pravega 0.4.0-rc3 build

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3295]
**Problem description**
While running longevity test in PKS cluster with Small IO workload on `0.4.0-rc3`, observed one particular Segment which is less than the scaling trigger (events/sec) all the time, doesn't get merged with neighbors during the entire longevity run.

Segment `1478` was created on Saturday (5 days ago) and the whole time it had the event write rate below the Scaling trigger `3 ev/s`. It's the long medium blue one in the middle of heat chart, key range `0.522` to `0.674`, and the event write rate at `~2 ev/s`. I would expect pravega to try and merge it with the neighbors.
![heatmap_12hrs](https://user-images.githubusercontent.com/41920518/51375338-9a6eb100-1b2b-11e9-8a62-c51bb2fd76c3.png)

![image](https://user-images.githubusercontent.com/41920518/51375241-5bd8f680-1b2b-11e9-9f1d-8d9d66dce9ad.png)

**Comment by shiveshr** [comment]
This is not an issue..
i just verified the condition we check to identify if a segment is a candidate for scaledown:

```
                    if (twoMinuteRate < targetRate &&
                            fiveMinuteRate < targetRate &&
                            tenMinuteRate < targetRate &&
                            twentyMinuteRate < targetRate / 2.0 &&
                            currentTime - startTime > TWENTY_MINUTES) {
                        log.debug("triggering scale down for {}", streamSegmentName);

                        triggerScaleDown(streamSegmentName, false);
                    }
```

`twenty-minute rate should be less than half of target rate` .. Since this segment gets steady traffic of `2 e/s` then all rates (2 min, 5 min, 10 min and 20 min rates) would be converging towards 2 `e/s`.. and the above condition would make this segment a stable one without us treating it as a scale down candidate.
