### ISSUE TITLE
Authentication failure messages in logs with auth-enabled Standalone mode

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#3296]
**Problem description**
1. Enable ``auth`` in ``standalone-config.properties``:
```
singlenode.enableAuth=true
singlenode.userName=admin
singlenode.passwd=1111_aaaa
singlenode.passwdFile=../config/passwd
```
2. Start Pravega in standalone mode: ``./gradlew startStandalone``

3. Observe stack traces like the following showing up again and again in the logs: 
```
[INFO ] 2019-01-18 00:00:09.964 [core-17] i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].
[INFO ] 2019-01-18 00:00:10.274 [grpc-default-executor-12] i.p.c.s.r.g.v.ControllerServiceImpl - getCurrentSegments called for stream _system/_requeststream.
[ERROR] 2019-01-18 00:00:10.275 [grpc-default-executor-12] i.p.c.s.r.g.v.ControllerServiceImpl - Controller api failed with authenticator error
[WARN ] 2019-01-18 00:00:10.278 [grpc-default-executor-13] i.p.c.s.i.ControllerImpl - gRPC call for getCurrentSegments with trace id 0 failed with server error.
io.grpc.StatusRuntimeException: UNAUTHENTICATED: Authentication failed
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO ] 2019-01-18 00:00:10.309 [core-9] i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[1]: EvictedStreamSegments Count = 0, Active = 3
[INFO ] 2019-01-18 00:00:10.309 [core-10] i.p.s.s.c.StreamSegmentContainerMetadata - SegmentContainer[0]: EvictedStre
```

Note: 
- Even with these exceptions, reader/writer client applications work properly; This is true with Pravega client built using the latest code. I got similar exception messages on the client side too with Pravega client of version 0.3.2, and with that version, the client-side operations also failed. 
- @adrianmo has mentioned the same issue in PR #3235.  

**Problem location**
``ControllerServiceImpl.authenticateExecuteAndProcessResults(..)``

**Suggestions for an improvement**

**Comment by ravisharda** [comment]
While debugging another issue, noticed an instance of this issue when checkAuthorization(..) of AuthHelper is invoked with arguments: ``resource="_system/_requeststream", and expectedLevel = "READ"``. While it is really that authorization fails, the logged message (``Controller api failed with authenticator error``) and the message sent to the stream observer (``UNAUTHENTICATED / Authentication failed``) wrongly indicates that authentication has failed. Just something to note.

**Comment by vijikarthi** [comment]
While working on https://github.com/pravega/hadoop-connectors/issues/64, I have found number of issues related to controller security and standalone cluster. Instead of creating a new issue, just thought of posting the details as comment in this issue since it is related. 

#1) Credentials is null (looks like the environment variables that contains security token is not visible in this code?)
https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java#L184

#2) delegation token is empty - We get the token in getOrRefreshDelegationTokenFor() call in the same method but it was not used (which contains the correct delegation token)
https://github.com/pravega/pravega/blob/master/client/src/main/java/io/pravega/client/stream/impl/ControllerImpl.java#L737

#3) service port is empty
https://github.com/pravega/pravega/blob/master/controller/src/main/java/io/pravega/controller/server/ControllerServiceStarter.java#L169
```
            ClientConfig clientConfig = ClientConfig.builder()
                    .controllerURI(URI.create((serviceConfig.getGRPCServerConfig().get().isTlsEnabled() ?
                            "tls://" : "tcp://") + "localhost:" + serviceConfig.getGRPCServerConfig().get().getPort()))
                    .trustStore(serviceConfig.getGRPCServerConfig().get().getTlsTrustStore())
                    .validateHostName(false)
                    .build();
```	

#4) ClientConfig is missing security credentials (could be related to #1)
https://github.com/pravega/pravega/blob/master/segmentstore/server/host/src/main/java/io/pravega/segmentstore/server/host/stat/AutoScaleProcessor.java#L168

#5) Incorrect user credential is used
https://github.com/pravega/pravega/blob/master/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L261

**Comment by vijikarthi** [comment]
I don't think that this issue is resolved. Please see my comments in https://github.com/pravega/pravega/pull/3756#pullrequestreview-234808314
