### ISSUE TITLE
Update Bookkeeper image to use official image as base

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega#3311]
**Problem description**
We want to enable Bookkeeper metrics in Pravega but our current Bookkeeper image cannot support this feature. The related issues are [Pravega operator Issue 63](https://github.com/pravega/pravega-operator/issues/63) and [Pravega Issue 3101](https://github.com/pravega/pravega/issues/3101).

To enable Bookkeeper metrics we need to configure Bookkeeper. The way to configure Bookkeeper is to override configurations in `bk_server`, which is already done [here](https://github.com/pravega/pravega/blob/master/docker/bookkeeper/entrypoint.sh#L40). This works for now but is not enough for enabling Bookkeeper metrics as there are too many configurations that are available. 

**Problem location**
In Pravega Bookkeeper [Dockerfile](url) and [Entrypoint.sh](url)

**Suggestions for an improvement**
The official Bookkeeper image has a nice way to easily modify configurations by passing environment variables with a prefix `BK_` or `ZK_`. It has a script that can parse env variables with those prefixes and override the configuration if their names match. Details can be found [here](https://github.com/apache/bookkeeper/blob/master/docker/README.md#environment-variable-names-that-mostly-used-for-your-configuration)

It would be nice if we can use the official Bookkeeper image as our base image and customize it from that.

**Comment by Tristan1900** [comment]
@adrianmo @fpj Any inputs for this issue would be appreciated!

**Comment by adrianmo** [comment]
I've had the idea of basing our BK Docker image on the official for a long time, but I haven't seen a real need to do so until now. IMO, instead of porting scripts from the official image and applying patches, we should attempt to create a _wrapper_ image around the official one. The advantages I can see are the following:

- Remove duplicated code from our Docker image scripts and build process.
- Take advantage of official addons and features, like using `BK_` env vars as configuration or health check scripts.
- Outsource most of the maintenance work. We just need to maintain our Pravega-related wrapper code.
- Easy updates. Just changing the image tag.

**Comment by adrianmo** [comment]
@eolivelli, as a BK contributor, do you think we are making the right decision?

**Comment by eolivelli** [comment]
I think this is a great idea.
Expecially if Pravega teams plans to help maintaining such image with the community.
