### ISSUE TITLE
SegmentAggregates rate is initialized with 0 which causes slow start in terms of rate calculation

### ISSUE THREAD

**Issue by shiveshr** [pravega/pravega#3324]
**Problem description**
When we are calculating the 20 minute rate it's based on an exponential running average that has a half life of 20 minutes and it updates the value every 5 seconds. The interesting bit is how it is initialized, it sets it to zero initially, and then every 5 seconds there after it is updated. If the value is still zero it is set to the new value. Otherwise it updates the value normally. So what if for the first 5 seconds after the segment is created it has lower than normal traffic (this seems likely, as the client will take a bit to even locate the new segment). Then that datapoint can become highly influential. For example if that data point it .5 events/sec then even after 20 minutes of 2 events/sec the running average should be ~1.4 events/sec. This is below the 1.5 event/sec threshold for scaling down. Hence this happens often. However IF the client's first data-point was fairly normal and the scaling didn't happen right away, it likely wouldn't ever happen because it wouldn't ever sustain < 1.5 event/sec for 20 minutes.

**Problem location**
SegmentAggregates.

**Suggestions for an improvement**

Where the values are being initialized for the first time, they shouldn't be initialized to zero, but rather `targetRate * TICK_INTERVAL`. This will bias against any immediate scaling in either direction by starting with the assumption that we are already at the target rate.

**Comment by fpj** [comment]
It sounds right that departing from the first sample can have the effect described here, that even after 20 minutes of 2 events/s (except for the first sample), we will have a 20-minute rate of roughly 1.3-1.4. The initial value in this case has a pretty significant influence

Setting it to be target also has a similar problem, though. I was playing with numbers on Excel and I can see that if I set the target to be say 5 events/s, the first rate to be 0.2/s, and all other samples to be 2 events/s, then I still have a 20-minute rate that is greater than 3 events/s, which wouldn't allow my stream to scale down.

I also played with the alpha constant a bit, and if we want it to react faster to changes, then we need to increase the value of alpha. For example, multiplying by 10 makes the 20-minute rate roughly 2 events/s. We might need to calibrate the alphas instead of making the change suggested here.

Hopefully I have done my math right...
