### ISSUE TITLE
Improve the latency for small message sizes

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#3590]
**Problem description**
Currently for 100 bytes event size, the average latency is 8 ms observed in white cluster (lag unitas).
event after this PR : https://github.com/pravega/pravega/pull/3482 
the performance improvement is observed only in 1K and above size messages.

**Problem location**
The problem location is pravega client. the pravega client batch size needs to be tuned so that
for small size message there will be improvement in the latencies.

**Suggestions for an improvement**
Actually, the batch size can be set as  producer property; so that user application can configure it according to the event size requirements.

**Comment by RaulGracia** [comment]
Pravega does not write an event to the storage immediately after it is received by the Segment Store, and this is specially true for small ones (<100 bytes). Instead, internally the Segment Store performs a kind of micro aggregation or batching and submits such batches to Bookkeeper. As you noticed, a downside of this approach is that we add some latency to individual write operations (e.g., for 100 byte events, Bookkeeper may absorb writes with a _95th latency_ of 3ms-5ms, while for Pravega this value may be 15ms-20ms). However, this strategy allows a single Segment Store to support +300K writes/second, whereas a 3-bookie ensemble saturates at 60K-70K writes/second (i.e., a single Bookie supports 20K writes/second with the aforementioned latency). I think that this is design "trade-off" more than an issue, but maybe it would be interesting to have more control (e.g., via configuration) on the way such "batching" is performed, so we can make the system more throughput or latency sensitive.

**Comment by andreipaduroiu** [comment]
This is not 100% correct. For a single stream of small writes, we can match BooKeeper's latency. If it does 3-5ms, we will also have 3-5ms (our overhead is very small, measured in less than 1ms). If we have concurrent writes, they will be aggregated and their combined latency will be whatever BookKeeper takes to write the bigger write. The Segment Store does not wait in order to aggregate more appends. It does micro-batching using a dynamic algorithm that does not introduce latency. Please see this blog post for an explanation of how it is done. http://blog.pravega.io/2019/04/22/events-big-or-small-bring-them-on/

**Comment by RaulGracia** [comment]
Thanks for the input, @andreipaduroiu. Considering your comment, what do you think that is the source of the higher latency that @kmgowda is reporting here? In some experiments I performed some weeks back, here you have an instance of such a behavior that at I (wrongly) thought to be related to the effect of micro-batching on latency:

![image](https://user-images.githubusercontent.com/717112/57644036-84de3500-75bb-11e9-8d14-00a90a0ec07b.png)

If this is not the expected behavior, then we need to dig further to understand the cause for this.

**Comment by andreipaduroiu** [comment]
When you measure latency, do you do it from the client or using the Segment Store's metrics? The client does other things on top of the Segment Store that could lead to this.

**Comment by RaulGracia** [comment]
The benchmarks for Bookkeeper have been performed with the [Bookkeeper benchmark](https://github.com/apache/bookkeeper/tree/master/bookkeeper-benchmark), whereas the Pravega ones have been performed with our [benchmarking tool](https://github.com/pravega/pravega-benchmark). Do you suspect that this may be an artifact of our benchmarking tool measuring latency?

**Comment by andreipaduroiu** [comment]
The benchmarking tool uses the Client to communicate with the segment Store. The Client does additional processing, including batching, for small events. That could result in added latency.
