### ISSUE TITLE
SegmentStore failed to start when external connectivity enabled on PKS. Error "Unexpected service type . Exiting..."

### ISSUE THREAD

**Issue by deenav** [pravega/pravega#3614]
**Problem description**
There is an error `Unexpected service type . Exiting...` in Segmentstore when Pravega external connectivity is enabled in PKS environment.

SegmentStore logs:
```
# kubectl logs -f po/pravega-pravega-segmentstore-0
Waiting for pravega-bookie-0.pravega-bookie-headless.default:3181
Connected to pravega-bookie-0.pravega-bookie-headless.default:3181
Waiting for pravega-bookie-1.pravega-bookie-headless.default:3181
Connected to pravega-bookie-1.pravega-bookie-headless.default:3181
Waiting for pravega-bookie-2.pravega-bookie-headless.default:3181
Connected to pravega-bookie-2.pravega-bookie-headless.default:3181
Running in a Kubernetes environment and managed by the Pravega Operator with external access enabled
Unexpected service type . Exiting...
```

Deployment Details:
```
Pravega-Operator image: pravega/pravega-operator:0.3.2
Pravega build used : 0.5.0-2205.02f1c00
Zookeeper-operator image: pravega/zookeeper-operator:0.2.1
```

Environment details: PKS / K8 with large cluster:
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
10 worker nodes @ 2xlarge.cpu(16 cpu, 16 GB Ram, 64 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend 
```
**Problem location**
SegmentStore bootstrap script

**Comment by adrianmo** [comment]
@deenav I've investigated the issue and it looks like the root cause is that the service account that is configured in the SegmentStore pod doesn't have permissions to obtain the service information.

Checkout the [Use non-default service accounts](https://github.com/pravega/pravega-operator#use-non-default-service-accounts) in the operator readme file. You will need to create a new service account, role, and role binding, and then configure it in the manifest. 

Let me know if that helped.

**Comment by deenav** [comment]
Hi @adrianmo, After creatinga new service account, role, and role binding, and then configure it in the manifest, SegmentStore working fine with external-connectivity enabled on PKS cluster. 

I have opened https://github.com/pravega/pravega-operator/issues/161 for documenting the steps required for enabling the exteral-connectivity. 

Hence I am closing this issue.
