### ISSUE TITLE
Support for TLS certificate reload

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega#3652]
**Problem description**
Enhance Pravega to support TLS certificate hot-reload, to support certificate rotation and to interoperate with certificate authorities which issue short-lived certificates.

At present, Pravega has no support for TLS certificate reload; one must restart the Pravega processes by hand, which is disruptive to existing connections, and operationally complex.  

Two scenarios where this issue manifests:
1. The popular Let's Encrypt certificate authority issues certificates that are valid for a mere 3 months, necessitating that certificate rotation be well-supported by the application.
2. the cert-manager extension for Kubernetes has a peculiar way of issuing certificates; in the course of provisioning a certificate for Pravega purposes, it first issues a temporary certificate that is self-signed, and then issues another certificate a few minutes later.

**Suggestions for an improvement**
- Implement a file watcher that monitors the configured .key/.crt files.
- Whenever the cert changes, reload the  `SslContext` and use it on subsequent connections.  Any outstanding connection would remain intact.
- deferred: ~Consider using .key/.crt files rather than a keystore, for consistency between SS and controller.~
- deferred: ~Support hot reload on the controller~

**Comment by ravisharda** [comment]
@EronWright I'd like to assess the priority of this issue. 

W.r.t scenario 1: My understanding is that this enhancement can be highly beneficial w.r.t. operational overheads, but it's not something we couldn't live without for now. More so, as, it is not uncommon to refresh certificates in production under a planned maintenance cycle. That being said, it's certainly something that should be addressed at the earliest.

However, w.r.t scenario 2, it seems like this issue might be a blocker. Is that the case? If yes, this enhancement will need to be assigned a higher priority, I think.  

Could you please elaborate a bit more about the importance of addressing this, so that an appropriate priority can be assigned to this issue?

**Comment by EronWright** [comment]
Right, scenario (2) is driving the urgency.    

Cert-manager produces a K8 secret (containing a .key/.crt pair of files), then updates the content within a few minutes, then updates it again every few months.  K8s takes care of mounting the secret files into the pods.   The challenge is to ingest the updated certificate whenever the files change.   The suggestion that I outlined is (to my knowledge) the cleanest way to solve it.  The use of keystore format adds undue complexity because of the need for conversion.

**Comment by EronWright** [comment]
The latest plan is to use Ingress w/ TLS for controller, plus native support for reload in segment store.
