### ISSUE TITLE
TableSegment: Throttling

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#3700]
**Problem description**
Throttle incoming updates if background indexing falls too much behind.
While updates can happen at the speed of ingesting new writes, background indexing has more work to do so it can run at a slower pace. A rapid burst of updates can be quickly accepted and create a backlog in the indexing. While a normal execution wouldn't be too much affected, a container recovery would prevent all access to this Table Segment until the background indexing caught up.

Running SelfTester with these arguments will cause very fast updates and gets (because they're cached) but the background indexer takes a long time to process the 1M updates in this test.
`-Dtarget=SegmentStoreTable -Dbkc=0 -Dc=1 -Ds=1 -Dsc=1 -Dws=100 -Do=1000000 -Dp=1000 -Dtcu=false -Dtct=1`

Even though all latencies are well within reasonable limits, it took 6.5 minutes for this test to wait, with the last 6 minutes spent on background indexing to complete.

Sample result (actual times may vary based on hardware and other applications running).
```
0:06:29.297 [Reporter]: 1000975/1000000; Ops = 0/102034; U/G/GK:1000975/173/6336; Data: 237.1 MB; TPut: 0.0/24.2 MB/s; TPools (Q/T/S): S = 3/4/80, T = 0/1/80, FJ = 0/0/1.
0:06:29.297 [Reporter]: Operation Summary
0:06:29.297 [Reporter]:     Operation Type |   Count |  LAvg |   L50 |   L75 |   L90 |   L99 |  L999
0:06:29.298 [Reporter]:       Table Remove |  108582 |     9 |     4 |    12 |    23 |    63 |   115
0:06:29.298 [Reporter]:       Table Update |  892393 |     9 |     4 |    12 |    23 |    61 |   114
0:06:29.299 [Reporter]:          Table Get |     173 |    50 |    47 |    55 |    68 |   109 |   139
0:06:29.300 [Reporter]:  Tbl Iterator Loop |   27974 |     2 |     3 |     3 |     3 |     5 |    13
```

**Problem location**
Container Table Index/ WriterTableProcessor

**Suggestions for an improvement**
- Create a class in common that implements the "Leaky bucket" throttling algorithm.
    - `<T> T CompletableFuture<T> add(int size, Supplier<CompletableFuture<T>> toExecute)` will request the execution of some task subject to having enough capacity to accomodate the given `size`. The execution will be blocked (queued up) until there is sufficient capacity for `size` to be added, at which point `toExecute` will be invoked and the requested size will be reserved. If `toExecute` fails, then the allocated capacity is subtracted.
    - `void release(int size)` will remove the given size from the bucket and trigger the execution of any eligible updates, in the order in which they were received. The order is important since we need to execute the updates in the order in which we received them, even if that results in sub-optimal scheduling.
    - There should also be a method (constructor/initialize) that can set the initial capacity.
    - `close`: cancels any outstanding queued tasks and rejects any new ones.
- There will be an instance of this bucket per active TableSegment.
    - The `WriterTableProcessor` notifies every time it completes an indexing iteration (via `notifyIndexOffsetChanged` and we can piggyback onto this to invoke the bucket's `release` method.
    - `put`/`remove` will be run through `add` where the number of items in each batch will be passed as `size`.

**Comment by fpj** [comment]
@andreipaduroiu thanks for putting this together. Overall, the scheme looks good, but let me clarify a few things:

- The choice of the initial capacity is important. If we choose it small, then we could be limiting ourselves unnecessarily. If we choose it large, then that's ok because there will be an initial burst, which the indexer will struggle with a bit, but then it will self-regulate by releasing credits at the pace it can process. At the moment, it only seems to be a problem to choose a small value.
- Another question is around the size of the tasks. If it can be arbitrary, then is it possible that I call `add` for a task with a size that can't be fulfilled. I suppose the answer is that we throw if there is an attempt to add a task that exceeds the total number of credits, available + used.
- The tasks are batches of updates, right? As such, the tasks that we are adding do not seem to be indivisible. For example, say that we add a task with 100 updates, and we have 99 credits available. I think in principle we should be able to process the 99 updates. We may choose not to optimize in this way, which is fine for now, I'm only trying to understand if I got the right idea.
- The choice of size might also matter for the overall throughput, in a similar way of what we had to do for the operation processor. Are we grouping updates opportunistically or otherwise how are deciding on the size of the tasks?

**Comment by andreipaduroiu** [comment]
Yes you are correct. A single "credit" is equal to 1 Update or 1 Remove. A batch of N updates will require N credits and a batch of N removals will require N credits.

The max limit will need to be sufficiently large. I am considering something like 10,000, which can also be set as the maximum number of items that we accept in a batch.

As for divisibility, if we have 99 credits available, then we cannot process a batch of 100, since by contract, batches are atomic. Also, if we have 99 credits, and a batch of 100, then several of size 1, 2, 3, 4, 5, ..., then we could optimize this, but we'd risk introducing starvation. We'd always be prioritizing smaller batches and as such, larger batches may never get a chance to be processed. Fixing that fairly would introduce even more problems, and I prefer not to do it in this initial cut.
