### ISSUE TITLE
Sporadic failure in EndToEndStatsTest.testStatsCount

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3715]
**Problem description**
Observed Travis failure in `EndToEndStatsTest` integration test:
```
io.pravega.test.integration.endtoendtest.EndToEndStatsTest > testStatsCount FAILED
    java.lang.NullPointerException
        at io.pravega.test.integration.endtoendtest.EndToEndStatsTest.testStatsCount(EndToEndStatsTest.java:117)
```

**Problem location**
`EndToEndStatsTest`

**Suggestions for an improvement**
Fix the test.

**Comment by kevinhan88** [comment]
The issue was caused by a map object inside a mocking StatsLogger; the map has no writing protection which eventually caused NullPointerException for looking up object in map.
The solution could be to replace the map object with Micrometer SimpleMeterRegistry, which has decent protection to the map inside it. In addition, testing SimpleMeterRegistry is closer to production runtime, compared to test a bare map object in a mocking StatsLogger.
The PR will be out tomorrow (Apr 31st).

**Comment by kevinhan88** [comment]
The failure happened to r0.5 branch.

**Comment by kevinhan88** [comment]
https://github.com/pravega/pravega/pull/3732 created
