### ISSUE TITLE
SegmentStore : Several NullPointerException in SegmentAggregator while running against ECS

### ISSUE THREAD

**Issue by sachin-j-joshi** [pravega/pravega#3724]
**Problem description**
When running system tests against ECS, during the StorageWriter iteration several NullPointerException are observed (more than 8K)

Below is one stack trace
> 2019-04-29 14:58:02,446 51039 [Thread-2] ERROR i.p.s.server.writer.StorageWriter - StorageWriter[3]: Iteration[79].Error.
> java.lang.NullPointerException: null
> 	at io.pravega.segmentstore.storage.AsyncStorageWrapper.write(AsyncStorageWrapper.java:93)
> 	at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$flushPendingAppends$17(SegmentAggregator.java:775)
> 	at io.pravega.segmentstore.server.writer.SegmentAggregator.lambda$createSegmentIfNecessary$40(SegmentAggregator.java:1138)
> 	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
> 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
> 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
> 	at java.lang.Thread.run(Thread.java:748)

**Problem location**
The problem seems to be createSegmentIfNecessary in SegmentAggregator.java
The code is expecting the segment to be not present, but finds the segment present .
This results in null being passed to next lamda

https://github.com/pravega/pravega/blob/40f6fe09474b5b4f4a5e0bbeff54d798f7042516/segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/SegmentAggregator.java#L1125

> return Futures
>                     .exceptionallyExpecting(
>                             this.storage.create(this.metadata.getName(), rollingPolicy, timeout),
>                             ex -> ex instanceof StreamSegmentExistsException,
>                             **null)** //====> passing null
>                     .thenComposeAsync(handle -> {
>                         **_this.handle.set(handle);_**   //===> The handle is set to null here. which ultimately throws
>                         return toRun.get();
>                     });
> 

**Suggestions for an improvement**

- Handle null correctly.
- This seems to be symptom of a deeper problem of mismatch between what segment store thinks the state of the segment is vs what is actually in storage.

**Comment by andreipaduroiu** [comment]
This is how this happened:
1. We create a Segment mapped to Container X running on Segment Store A.
2. We append some data to this Segment, which makes it to Tier 1, but not yet to Tier 2. The `SegmentAggregator` for this segment (in A) is initialized and knows it does not exist (hence `handle == null`).
3. We get a hard failover and we have two instances of the same Container running at the same time on different Segment Store hosts. We now have instance A (old) and B (new). The `SegmentAggregator` on instance B is also initialized and has `handle == null`.
4. One of the following happens:
4.1. A creates the segment in Tier 1 and writes the append to it **OR**
4.2. B creates the segment in Tier 1 and writes the append to it.
5. If 4.1 happened, then B will attempt to re-create the segment, which will fail because it exists, and pass a null handle to the subsequent `write` (which, ironically, would have also failed due to `BadOffsetException`). If 4.2, happened, this would have resulted on instance A.

The fix for this is to `openWrite` the segment if it already exists and get the handle from there.
