### ISSUE TITLE
Sporadic failure in MetricsProviderTest.testGauge

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega#3786]
**Problem description**
Found a sporadic assertion error in `MetricsProviderTest.testGauge`:
```
Error Message
java.lang.AssertionError: expected:<2> but was:<0>
Stacktrace
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.pravega.shared.metrics.MetricsProviderTest.testGauge(MetricsProviderTest.java:193)
```

**Problem location**
`MetricsProviderTest.testGauge`

**Suggestions for an improvement**
Fix the issue.

**Comment by kevinhan88** [comment]
Was able to reproduce the problem by repportGaugeValue over a huge number of times (e.g. 100k) and Gauge object might be lost.
This is caused by the approach that we always remove old gauge object and register new one to have the effect of update.
This approach is inside legacy code (e.g. https://github.com/pravega/pravega/blob/5964c97f3207d2949ffe7649e507fb31be4fadc9/shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java#L140), the migration didn't change the approach. I'm working on the improvement of this approach to make the code robust.
