### ISSUE TITLE
IO is not getting started with 3 SS and 4 Node Swarm setup

### ISSUE THREAD

**Issue by Richa-Srivastava** [pravega/pravega#3859]
**After setting up Docker Swarm setup with 4 nodes(1 Master & 3 Workers), IO is not getting started.**

All 3 Segments stores are getting distributed in all 3 nodes(out of 4) but as per segment store logs, we observed that all the 4 containers 0-3 are getting assigned to all 3 segment store. 
```
2019-05-30 10:29:43,846 401529 [core-8] INFO  i.p.s.s.h.ZKSegmentContainerMonitor - Container Changes: Desired = [0, 1, 2, 3], Current = [0, 1, 2, 3], PendingTasks = [], ToStart = [], ToStop = [].
```
It looks like controller is not properly distributing all 4 containers to 3 segment stores and hence segment store is not functioning properly.

Following is the Swarm setup deployed as per the document procedure:
```
3 Segment Store
2 Controller
4 Bookkeeper
1 Zookeeper
```

Attaching the logs for all the containers.
[4node3ssLog.zip](https://github.com/pravega/pravega/files/3239921/4node3ssLog.zip)

**Comment by sumit-bm** [comment]
Related issue #3041 

The docker swarm have been deployed as per the documentation available in http://pravega.io/docs/latest/deployment/docker-swarm/ and scale up procedures mentioned over there.

**Comment by shrids** [comment]
All the 3 SSS instances have the same published address which is causing the issue.
```
// published ip address for all three SSS instances.
-Dpravegaservice.publishedIPAddress=10.246.154.55
```

**Comment by sumit-bm** [comment]
@shrids We would like to know what would be solution for this case? 

It seems this issue is happening for swarm deployed in external client scenarios and as per following section in documentation http://pravega.io/docs/latest/deployment/docker-swarm/#scaling-pravega-segment-store-external-clients, scale segmentstore is a valid use case.

We have following use cases broken in swarm deployed in external clients. 

1. A deployment having multiple segmentstore replicas defined in `pravega.yml` 
2. Deployment started with single segmentstore instance and scale up later to multiple replicas.

**Comment by shrids** [comment]
@sumit-bm 
As I understand you are interested in the external client scenario(i.e. the Pravega client is not part of the SWARM cluster).
The documentation talks about two things
a. `docker service scale pravega_segmentstore=N` **cannot** be used to scale up the SegmentStore if you are using `PUBLISHED_ADDRESS`  (which is mandatory since we need external access)
ref: https://github.com/pravega/pravega/blob/master/documentation/src/docs/deployment/docker-swarm.md#scaling-pravega-segment-store-swarm-only-clients
b. The script `./scale_segmentstore N` should be used to scale up the segment store, since the intent here is to ensure `PUBLISHED_ADDRESS` is unique for ever segment store instance.

Could you confirm that you have tried using `./scale_segmentstore` for your deployment and you have configured `PUBLISHED_ADDRESS` environment variable for every host, which is unique/host ?

As I understand the script `scale_segmentStore` creates N separate  docker services for a SegmentStore , where N is the desired instance count of Segment store.

Let us know if you are still facing the issue with these pointers.

**Comment by sumit-bm** [comment]
@shrids we tried with `scale_segmentStore` and after segmentstores are scaled up IO failure had been observed. Also on a initial deployment with multiple `segmentstore` replicas IO failure had been observed in external client deployment.

I am not fully understand the point `b` you raised, to ensure `PUBLISHED_ADDRESS` is unique for every segmentstore instance, you need to give us a procedure if you think the procedure documented in deployment section is not valid / need correction / not clear enough as we tried that procedure and seems things are not working well.

One question, does the system test deploy swarm with deployment procedures documented? Have we tried external client deployment in system test with multiple segment store? Could you give a try deploying multiple segment store in external client procedure documented and i think that would clarify  you what issues we are facing.

**Comment by shrids** [comment]
Update: There is an issue with `scale_segmentStore` script.
As a work around we can manually create a new SSS instances by manually creating a docker service for segment store.

```
docker service create --name=pravega-sss-2 \
          --network pravega_default \
          --label com.docker.stack.namespace='pravega' \
          -p 12349:12349 \
          -e HDFS_URL=hdfs://hdfs:8020 \
          -e ZK_URL=zookeeper:2181 \
          -e CONTROLLER_URL=tcp://controller:9090 \
          -e JAVA_OPTS='-Dmetrics.enableCSVReporter=false -Dpravegaservice.publishedIPAddress=X.246.154.58 -Dpravegaservice.listeningPort=12349  -Dpravegaservice.listeningIPAddress=0 -Dbookkeeper.bkEnsembleSize=2 -Dbookkeeper.bkAckQuorumSize=2 -Dbookkeeper.bkWriteQuorumSize=2 -Xmx900m -XX:OnError="kill -9 p%" -XX:+ExitOnOutOfMemoryError -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError' \
          devops-repo.isus.emc.com:8116/nautilus/pravega:0.5.0-2260.b477eec segmentstore
```

**Comment by shrids** [comment]
@Richa-Srivastava I have updated the script in PR https://github.com/pravega/pravega/pull/3868 . Could you verify it and provide feedback ?

**Comment by shrids** [comment]
Thanks @Richa-Srivastava  verifying the fix.
