### ISSUE TITLE
Gradual Performance degradation and inconsistencies in performance

### ISSUE THREAD

**Issue by kmgowda** [pravega/pravega#4005]
**Problem description**
In 0.5 and in master ; its observed that upon continuous writing the performance drops gradually by more than 50%. For example, with 1K event size 10 writers, the performance starts at 80-100 MB/s and gradually drops to 40-50% on lagunitas cluster.
With connection pooling , this problem is reproducible with in 30 mins - 1hr.
without connection pooling, this problem prolongs and but its observed. 

**Problem location**
As now debugging points to following components.
1. Bookkeeper
            Bookkeeper is slows down over a period of time.  Need furthers debugging on this.
2.  Pravega client
           As on today , its just a guess that the Pravega client might not be pushing much data  over a period of time. 

3. Randomly JVM heap issues are observed; but its not consistent.

**Suggestions for an improvement**
1. Requires further debugging on above 1st and 2nd issues.
2. Bookkeeper version used for bare metal deployment is 4.7.3 ; need to be tested with bookkeeper 4.9.+ or which ever the latest version.

**Comment by RaulGracia** [comment]
I have observed an instance of this issue in a `small-key` longevity run. Please, have a look to the following plot:
![performance_after_degradation](https://user-images.githubusercontent.com/717112/61121874-a024ce00-a4a0-11e9-9c09-49a84e35f11d.jpg)

_Confirmation_: As you have also observed, the longevity application shows severe performance degradation as time passes (upper-left plot). The numbers plotted there come from the longevity manager itself, but we calculated throughput using just the number of events and the trend is similar.

_Progress_:
1) I wanted to understand if the problem was at the server side or not. To this end, the other 3 plots in the figure show benchmarks executed against the Segment Store service after +10 hours of longevity workload. Actually, these benchmark were running along with the `small-key` workload. As you can see, the benchmark tool shows good performance, just as the `small-key` workload did at the beginning of the experiment.
2) In the upper-right plot, there are two lines: in one, the benchmarking tool writes to a new Stream, whereas the other refers to the benchmarking tool writing to the "same Stream" used by the longevity experiment (changed the scope from `Scope` to `longevity` to do this test in the benchmark tool). Visibly, the performance results are similar.

_Conclusion_: The performance degradation seems neither related with the Segment Store (and its dependencies) nor with the Stream being used for long time. Given that you have observed this behavior with the benchmarking tool and I found the same with the longevity tool, this leaves us the _Pravega client as the main focus of investigation_. Do you agree?

**Comment by kmgowda** [comment]
yes, I witness the performance drop is observed as you showed in the upper left corner (plot 1).
but, when i see the degradation , I even observed that on other stream performance was better. so, its still goes to the suspicion on bookeeper or segment store.
But some time it regains performance as shown below.

![image](https://user-images.githubusercontent.com/7926048/61131399-c82f2400-a4d6-11e9-828f-f12ae469a022.png)

When this degradation occurred I missed the metrics ; so, I will post further observations soon.

But however, i agree client need attention but i do still suspect the bookkeeper performance too.

**Comment by RaulGracia** [comment]
@kmgowda the problems we are describing seem very different, right? The one I describe is an actual degradation of performance along time (several hours), but this plot seem to be a temporal stall of writes that is recovered after some time (several seconds). Even the IO workload used seems very different. Probably the reasons for both are completely different, so we need to probably split them in separate issues.

**Comment by RaulGracia** [comment]
This problem is not reproducing again in newer versions. If we detect something similar, we will create a new issue.
