### ISSUE TITLE
controller runtime log has exceptions when startup in pravega 0.5.0 version

### ISSUE THREAD

**Issue by frank-dkvan** [pravega/pravega#4093]
**Problem description**

2019-08-12 17:24:05,220 22146 [nioEventLoopGroup-2-1] ERROR i.p.s.p.n.ExceptionLoggingHandler - Uncaught exception on connection 10.226.112.46
java.nio.channels.NotYetConnectedException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0()(Unknown Source)

**Problem location**
run ~/pravega-0.5.0/bin/pravega-controller

**Suggestions for an improvement**

**Comment by shiveshr** [comment]
Could you please share additional logs (complete stack trace) so that we can give better insight into the cause for these exceptions. 
However, if these are temporary and only observed transiently during cluster bootstrap then one plausible cause could be as follows:
Controller makes use of internal pravega streams and also uses SegmentStore's table apis to store Pravega stream's metadata. If a controller is bootstraped before segmentstores are started, we may see connection related errors as controller tries to establish connection with segment stores to either create some internal streams or access some metadata.

**Comment by frank-dkvan** [comment]
> Could you please share additional logs (complete stack trace) so that we can give better insight into the cause for these exceptions.
> However, if these are temporary and only observed transiently during cluster bootstrap then one plausible cause could be as follows:
> Controller makes use of internal pravega streams and also uses SegmentStore's table apis to store Pravega stream's metadata. If a controller is bootstraped before segmentstores are started, we may see connection related errors as controller tries to establish connection with segment stores to either create some internal streams or access some metadata.

Hi when I start SegmentStore server first before the controller server starts, the exception above disappear...but...the SegmentStore server log has exceptions that SegmentStore got fail to connect controller  server.   by the way, do they need to connect each other?

**Comment by RaulGracia** [comment]
Hi @frank-dkvan, the Segment Store and the Controller are mutually dependent. The Controller needs the Segment Store to instantiate internal streams and write metadata to table segments, whereas the Segment Store requires the Controller to define a <segmentstore-container> assignment or to handle auto-scaling requests. So, these initial logs while both services are trying to contact each other are harmless and expected.
