### ISSUE TITLE
Reduce Metrics Cache Eviction Timeout

### ISSUE THREAD

**Issue by kevinhan88** [pravega/pravega#4149]
**Problem description**
Before the micrometer migration, there was a problem for the traditional counter, that if the counter object was evicted from the cache, then the counter was "reset", causing the "going up and down" effect on the metrics dashboard.
To fix the problem, we had to extend the cache eviction timeout to very long, by default 30 minutes. A lot of memory is occupied by the inactive metrics objects.

Refer https://github.com/pravega/pravega/issues/886 for the discussion.

With the micrometer migration, we started using StepRegistry, and in particular, StepCounter, which nailed down the above problem completely - without changing the Counter interface to application, the StepCounter implementation is actually a Rate.
Actually @tkaitchuck already pointed it out in https://github.com/pravega/pravega/issues/886 that we should change the counter to rate. Micrometer also states there shouldn't be counter at all and they changed the underlying implementation of counter to rate, solved the problem silently and elegantly.

How exactly the problem got solved? With StepCounter, each time the counter just report the delta, without concerning the previous value. Whether the previous counter object is there or not, is no longer important.
Now It is up to the back-end to determine how to aggregate the value for the counter:  to get the traditional view of counter, just aggregate for the period "infinite past to current".
To be honest, this absolute counter value is often useless, and not practical for a streaming system (imaging the counter of total read bytes for 2 years); for streaming we usually care a particular time window or period, which the rate is designed for!

With push mode, by default we export metrics every 10 seconds. The 30 mins cache eviction is now too long and unnecessary.

**Problem location**
MetricsConfig.java - metrics.dynamicCacheEvictionDurationMinutes

**Suggestions for an improvement**
Reduce the default metrics.dynamicCacheEvictionDurationMinutes down to 3 minutes from 30 minutes.

**Comment by fpj** [comment]
@kevinhan88 let's try to get closure on this issue. I was revisiting all the related information, including the discussion in issue #886, and the remaining questions I have are:

1- The description of this issue refers to `StepCounter`. I searched for it on the code and couldn't find any reference, but I did find references to `Counter`. Could you clarify how we are implementing rates in the code precisely?
2- Are you proposing that we strictly forbid absolute counters in the code? And if so, how would we enforce it? It might be ok to do it because values like the total size of a stream are not necessarily appropriate for metrics.
3- There is this is interesting observation from Chris Dail in the #886 issue about emitting and forgetting about it, which brings me to the question of whether we need a cache of metrics at all. If metrics are expected to be imprecise, and we could miss updates every now and again, then could we simply get rid of the cache altogether?

**Comment by kevinhan88** [comment]
@fpj please see my responses below:
1. see this line: https://github.com/pravega/pravega/blob/94482e51e5324075d0be8d9c81a3871faaa5ef32/shared/metrics/src/main/java/io/pravega/shared/metrics/StatsLoggerImpl.java#L84
CounterImpl in pravega is based on io.micrometer.core.instrucment.Counter, whose concrete implementation is StepCounter. 

2. There is no need to strictly forbid using absolute counter, but we should always judge whether we could use rate instead, which is more powerful and flexible. Please refer to Micrometer's document at https://micrometer.io/docs/concepts#_counters

3. Before Micrometer migration, we had to keep cache to hold counter object. This is just a workaround, because no matter how long the eviction window is, the counter may indeed get quite for more than that window and start counting again.

This is a fundamental problem for stateless application such as Pravega to maintain a state.

With Micrometer's implementation, which is backward compatible, we could nail down the above problem. Micrometer no longer keep the state of counter, instead it publishes whatever the delta after the previous publishing. This stateless approach fits Pravega much better.

In theory we may get rid of metrics cache completely, though I didn't think it through. One immediately concern is the performance, as each time we have to create metric object from scratch if no cache at all.

The balance might be that we still keep cache, but keep it minimum, as the associated PR does.
