### ISSUE TITLE
StreamSeekTest.testStreamSeek fails sporadically

### ISSUE THREAD

**Issue by andreipaduroiu** [pravega/pravega#4238]
**Problem description**
```
io.pravega.test.integration.StreamSeekTest > testStreamSeek FAILED
    java.util.concurrent.ExecutionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to createing stream: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null, timestampAggregationTimeout=0)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at io.pravega.test.integration.StreamSeekTest.createStream(StreamSeekTest.java:229)
        at io.pravega.test.integration.StreamSeekTest.testStreamSeek(StreamSeekTest.java:120)
        Caused by:
        io.pravega.client.stream.impl.ControllerFailureException: Failed to createing stream: StreamConfiguration(scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, 
```

**Problem location**
Either the test or the Controller. See below.

**Suggestions for an improvement**
This test was changed with #4181 to create 2 Streams concurrently. This does not seem to be handled nicely by the Controller as it sends two concurrent `CreateStream` requests to the Segment Store in the form of conditional updates on the same segment. Since they are both received at the same time, one will be rejected with `BadKeyVersionException` which is not handled/retried by the controller.

**Comment by shiveshr** [comment]
This requires fix on the test. 

The `createStream` is protected under a zookeeper based distributed lock. So we cannot have two concurrent create streams attempted for the same stream. And since we take this distributed mutex for creating a stream, we do not retry on BadKeyVersion exception in this flow. 

What has happened here is different though. Mark stream is a special internal stream associated with parent stream for storing watermarks. MarkStream's metadata and segment is created and deleted as part of `create` stream workflow and its lifecycle is tied to parent stream's lifecycle. 
Hence while creating a mark stream we do not take a different distributed lock but rely only on parent stream's distributed lock. 

Now this test attempts to create the stream and concurrently attempts to explicitly create mark stream (which is incorrect). 
So two concurrent execution contexts are attempting to create the mark stream - 
each working after acquiring different locks (first one locks the `stream` while second locks the `mark stream`) while both attempt to create mark stream. 
Mark streams should only be implicitly created as part of createStream and never explicitly as is being done in this test.

**Comment by shiveshr** [comment]
I stand corrected in my comment above. 
`createStream` is completely idempotent where we create each metadata record and handle BadKeyVersion and translate it to dataExists and handle it as a correct case. 

So even if we attempt to concurrently create MARK stream, it should not be a problem.

So maybe the problem is somewhere else. I am looking at the logs to see if i can determine the cause.
