### ISSUE TITLE
Expected behavior when Tier 2 is full

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#4503]
**Problem description**
I'd like to clarify what happens to segment store instances and what behavior clients observe when Tier 2 is out of space. In the case that Tier 2 runs out of space, we aren't able to write more segment data, and I wanted to clarify how that affects the operation of the segment store and how clients perceive it. 

A related question is how we get out of this situation. If segment stores aren't able to write to Tier 2, then would we be able to perform admin operations, even if manually, to say truncate streams to reclaim space?

**Problem location**
Segment store, Tier 2

**Suggestions for an improvement**
This is a clarification question and there isn't a clear suggestion for improvement at this point.

**Comment by fpj** [comment]
I vaguely remember asking this question before, and I have searched for an issue on it and couldn't find it. I created this issue so that we can have a record of it and a discussion if necessary.

**Comment by andreipaduroiu** [comment]
If Tier 2 is full, then supposedly we'd be getting some sort of error back from the respective adapter, which would prevent the StorageWriter from making progress.

This would quickly accumulate data in the Cache, at which point we begin throttling and halt all operations, resulting in a complete IO stall. I assume that, at the client, the requests will time out.

As for truncation, we cannot rely on the segment API (exposed by the Segment Store) because that is an operation in itself, which is subject to throttling.

We may do the following:
- Physically delete segments from Tier 2. For "best results", delete old, sealed segment to reduce nasty side effects on active operations. If the Segment Store ever receives a request for that segment, it will happily complain that it is missing and mind its own business afterwards.
     - It is important to follow up (after the cluster is unblocked) to delete the same segments via the Segment API, to ensure that whatever metadata we had about those segments is also deleted.
- Same can be done with truncation, but that will require more knowledge as to which chunks belong to which segment.

**Comment by medvedevigorek** [comment]
While understanding what manual steps one can perform to get the system out of such state, like removing some segments from Tier-2, etc is useful the more important to ensure the system can handle without committing suicide. As once that happens it is required to have someone with extended knowledge (data layout in Tier-2) to cleanup the things which is not really practical.  

Ideally the system should do the following:
1. Reserve certain space on Tier-2 to ensure **only** admin and other system operations can be performed once the used capacity is above that threshold. 
 2. Once the used capacity is above the threshold all new writes should be refused with proper error message on the user side. This way the user would know why the system rejects their requests and at the same time they can delete some of their data to free up space. 

It's not quite clear to me whether we need that threshold for Tier-2 or it can be actually implemented for Tier-1 only so even if nothing can be moved to Tier-2 the system still can process admin operations and recorded them in Tier-1. However this means the StorageWriter should give priority to system segment over user segment. 

Thoughts?

**Comment by andreipaduroiu** [comment]
It would be very difficult to implement such a thing in the Segment Store due to:
- Not all Tier 2s providing a clean API to get utilization
- Distributed nature of the system. Decisions are made at the Segment Container level; we have many of those spread out across multiple Segment Stores.

I kinda like suggestion #1 above (reserving some space on Tier 2). If we can do this at the mount level (or in the K8s PVC), then we can do the following:
- Once we hit the limit, we can stop user traffic (TBD how we can actually do this)
- Execute Stream/Segment retention which will invoke the correct Segment Truncate APIs, which will eventually clear some data out of Tier 2.


The least destructive solution though, would be something along these lines:
- We have a monitor for Tier 2 capacity
- If we reach or exceed some threshold (which is far from the 100% limit), we can do the following
    - Apply Size-based Stream retention more aggressively AND/OR 
    - Notify an operator (via an alert, if the deployed cluster supports it), to manually take action before it is too late.
- I prefer this approach since we are not suddenly going to fill up Tier 2 without prior warning (except if it is severely undersized). Just like we manage the Segment Store Cache, we should have plenty of warnings ahead of time before the situation becomes critical and we can take preemptive actions.

**Comment by sachin-j-joshi** [comment]
I suggest we have two configurable thresholds.
A soft limit after which we start issuing warnings and apply size based retention more aggressively. (as Andrei suggested.)
A hard limit after which we stop writing to tier-2.

For example - For FileSystem we can utilize apis like  https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getTotalSpace--

Assuming we can have equivalent way for HDFS and ECS.

**Comment by RaulGracia** [comment]
Another thing that may be good to have is a metric describing the amount of data actually stored in Tier 2. This would help us to react accordingly via an alert in the case we reach the hard limit.

**Comment by medvedevigorek** [comment]
Right, there wold be a need to have two thresholds - **Low** and **High**. 

- Low triggers an alert and anything else that may help to bring Tier-2 utilization below the low threshold

- High stops the user traffic and allows only Read and Delete operations as well as other mgmt activities so the user can free up some space. 

Note that in some cases upon exceeding Low threshold the user may decide to expand Tier 2 storage as there is nothing to clean up. The thresholds should be configurable so they can set them in such a way that gives them enough time to purchase an additional storage, etc. 

Next question is _how to monitor Tier 2 capacity?_
- Keep track of written/deleted bytes at Pravega level
  - It could be either at Segment Store or Segment Container level
  - Pros: It requires no special API support from Tier 2 provider 
  - Cons: It might be quite challenging due to distributed nature of the system 
- Rely on specific API support of Tier 2 provider. 
  - Pros: No special logic is required on Pravega
  - Cons: It requires Tier 2 provider to support an API to query capacity metrics 
  - Cons: It might be not possible with some Tier 2 configurations 

Btw, what if we try to solve this problem by leveraging Tier 1 only? 
- Once Tier 2 is full
  - Pause Cache flush into Tier 2 
  - Block new Writes but not Reads and Deletes 
  - Allow deleted segments to be replayed on Tier 2 by passing other segments from Cache 
- Once Tier 2 has available capacity resume Cache flushes

**Comment by kevinhan88** [comment]
Tested the storage full scenario using Benchmark:

1. After certain time, firstly confirmed that the long term storage of Pravega is indeed full:
(Note /mnt/tier2 is 100% full)
# df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay               51473020   8423868  40411432  17% /
tmpfs                    65536         0     65536   0% /dev
tmpfs                  4083868         0   4083868   0% /sys/fs/cgroup
/dev/sdb2             24854892   3766512  19802748  16% /dev/termination-log
/dev/sde              10190136  10173752         0 100% /mnt/tier2
/dev/sdc1             51473020   8423868  40411432  17% /etc/resolv.conf
/dev/sdc1             51473020   8423868  40411432  17% /etc/hostname
/dev/sdb2             24854892   3766512  19802748  16% /etc/hosts
/dev/sdb2             24854892   3766512  19802748  16% /tmp/dumpfile/heap
tmpfs                  4083868        12   4083856   0% /run/secrets/kubernetes.io/serviceaccount

2. Then the benchmark logs 0MiBs ingestion rate:
INFO io.pravega.perf.PerfStats -        0 records Writing,       0.0 records/sec,   0.00 MiB/sec,     NaN ms avg latency,     0.0 ms max latency
followed by:
WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for pingTransaction with trace id 0 and parameters [00000000-0000-0000-0000-00000000000a, 89999] failed with server error.
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 299999906321ns

3. checking segmentstore logs, throttling were in effect.
2020-05-21 21:28:25,033 2050388 [core-27] WARN  i.p.s.server.logs.Throttler - Throttler[1]: Processing delay = 25000ms (Max=true, Reason=Cache).
2020-05-21 21:28:25,033 2050388 [core-27] WARN  i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 25000ms (Max=true, Reason=Cache).

4. controller logs looked normal

(check out the attached logs for more details)

**Comment by kevinhan88** [comment]
[benchmark.log](https://github.com/pravega/pravega/files/4664989/benchmark.log)
[controller.log](https://github.com/pravega/pravega/files/4664991/controller.log)
[segmentstore.log](https://github.com/pravega/pravega/files/4664993/segmentstore.log)

**Comment by kevinhan88** [comment]
After the LTS(Long term storage) got full, SSS got into throttling mode as expected, and the client was showing 0 ingestion rate, which is also expected.
However, seems SSS stuck on the throttling even after the LTS has been freed up with some space:

2020-05-27 22:58:12,982 104056220 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=22458383990784] Updating table segment WireCommands.UpdateTableEntries(type=UPDATE_TABLE_ENTRIES, requestId=22458383990784, segment=_system/_tables/scopes, tableEntries=WireCommands.TableEntries(entries=[WireCommands.TableKey(data=UnpooledHeapByteBuf(ridx: 0, widx: 8, cap: 8/8), keyVersion=-1)=WireCommands.TableValue(data=UnpooledHeapByteBuf(ridx: 0, widx: 16, cap: 16/16))])).
2020-05-27 22:58:19,878 104063116 [core-19] WARN  i.p.s.server.logs.Throttler - Throttler[0]: Processing delay = 25000ms (Max=true, Reason=Cache).

The client (in this case Benchmark test) showed the following error:
2020-05-27 23:03:13:062 +0000 [grpc-default-executor-2] WARN io.pravega.client.stream.impl.ControllerImpl - gRPC call for createScope with trace id 2608167104205893045 and parameters [mayforce] failed with server error.
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 299999470269ns

**Comment by fpj** [comment]
Do we know what happens to the segment writer? As per @andreipaduroiu's description it will prevent the storage writer from making progress, and I'm wondering if this is stopping the storage writer altogether as it stops on critical errors:

https://github.com/pravega/pravega/blob/477f39b840a8ce1e2158e9ba924d393ea5275c0a/segmentstore/server/src/main/java/io/pravega/segmentstore/server/writer/StorageWriter.java#L162

**Comment by kevinhan88** [comment]
Here's what happened per the investigation.
. First of all, in case of disk full, a general IOException was thrown up to StorageManager, which indicates "No space left" in the exception content. NOTE: the write was partially done.
. Unfortunately StorageManager doesn't consider the exception is critical, per the existing implementation, so SM continues its operation, as if the above write was successfully.
. The following write gets BadOffsetException due to the partial write. Again there's no mechanism to handle the situation so SM keeps trying again and again.
. Cache is then full due to no flush can be done, hence throttling is in effect for ever.

**Comment by kevinhan88** [comment]
I would suggest we solve the problem in a bigger picture, by introducing the mechanism to handle bad write.

Disk full is just one case of bad write; we may have bad disk scenario, checksum verification failure and so on.

After each write, we need to verify the write was indeed successful, by checksum or similar mechanism. Of course, disk full exception is a straight checksum failure.
Once we encounter bad write situation, depends on the nature, we could try a couple more times (say a disk portion is broken, or a particular API call failed), or simply stop there.

When chunk manager is in place, the retry mechanism could also make use of it.

If there's a need to escalate (e.g. disk full, or write failed for too many times), then the controller is notified by the situation, metrics/alert is updated.

We must ensure Tier1 is persisted properly, metadata is synced up to reflect the bad write; cache can be cleaned up(to be discussed)

Client will see why it's being blocked.

Once the LTS issue has been fixed, rebooting to resume Pravega. Alternatively to do it in fancy way, we could design certain signal to be sent to controller.

**Comment by medvedevigorek** [comment]
@kevinhan88  what was the observed behavior in 1.1 and 1.2 cases once LTS got some free space?

**Comment by kevinhan88** [comment]
@medvedevigorek in case of 1.1, the client wasn't aware of the problem happening on server, so it kept sending more requests until the cache throttling was triggered.
In case of 1.2, the client was aware of the problem, and stopped sending more data. No throttling was triggered.

**Comment by medvedevigorek** [comment]
Yeah, I assume client may not know that LTS is full and will keep writing. The question here is whether the entire stack (including client and segmentstore) recovers automatically once LTS gets additional space. I would assume it should recover without the human intervention but not sure whether it was confirmed or not.

**Comment by kevinhan88** [comment]
It depends on where the failure happens:
In case of 1.1, where only partial stream payload got written, it's confirmed SSS cannot recover without human intervention. We don't have code to handle the scenario.
In case of 1.2, where stream header (metadata) write failed, it's confirmed SSS (and then the client) can recover without human intervention.
