### ISSUE TITLE
Update junitVersion to 5.xx in gradle.properties

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega#4554]
In pravega gradle.properties, 
junitVersion=4.12   is used.

Request is to update to version 5.xx
Requirement is to run junit tests in specific order for system tests. Also, to have dependency of one test on another. 

Need this annotation of junit 5.x to support this.

@TestMethodOrder(OrderAnnotation.class)

**Comment by ravisharda** [comment]
@Raghuveera-Rao why do you want the tests to run in a particular order or make them dependent on each other? Making tests depend on one another is a bad practice, IMO. 

Keeping tests independent has a lot of benefits: 

* Tests can be run in parallel - all together or in any combination
* Each test can be run solo (say to debug a particular use case)
* Each test has a known good starting state, so it makes it easier to debug each test and see what it is doing by looking at the code

**Comment by Raghuveera-Rao** [comment]
> @Raghuveera-Rao why do you want the tests to run in a particular order or make them dependent on each other? Making tests depend on one another is a bad practice, IMO.
> 
> Keeping tests independent has a lot of benefits:
> 
> * Tests can be run in parallel - all together or in any combination
> * Each test can be run solo (say to debug a particular use case)
> * Each test has a known good starting state, so it makes it easier to debug each test and see what it is doing by looking at the code

I have few scenarios where I order becomes necessary:-
create scope
create stream in scope
alter state of stream
delete stream
delete scope.

If order is not guaranteed, then each test has to perform few steps each time(example:- creating scope).  This may not be efficient. So providing order guarantee is needed in this scenario. 

Junit 5.xx provides this feature and this feature is also present in testng (using dependsOn).

**Comment by ravisharda** [comment]
Trying to reduce the time taken for running tests by making them depend on one another is an unnecessary and local optimization: it might reduce the time taken to run the test suite by a bit but can cause a ton of issues, including these: 
* Hard to run them in parallel (and therefore harder to make them faster)
* Hard to debug them when issues arise, as the state the test depends on is not visible directly in the code
* Flaky tests (fr example, one test may be dependent on state created by another test that ran 10 tests before it, and some new test was introduced between them)

Remember, it is not a human running these automated tests. In manual testing, it can help to organize tests in a way where one test setups the state for another. In automated testing, keeping tests independent and "free of execution order" has many benefits (some of which I listed before)

If your concern is repeating the code that creates the state for the test - for example, creating the Pravega scope for multiple tests - we can, of course, abstract it out into reusable classes/methods, so that the code is not repeated. 

We should keep the tests independent, as they are today.

**Comment by andreipaduroiu** [comment]
I think he's referring to system tests. We run system tests using the junit framework.

**Comment by ravisharda** [comment]
> I think he's referring to system tests. We run system tests using the junit framework.

Yes, I got that. Keeping tests independent is useful for automated system tests as well. (Here's a nice articulation on test isolation: https://martinfowler.com/articles/nonDeterminism.html#LackOfIsolation)
