### ISSUE TITLE
ArrayIndexOutOfBoundsException if rawClient create a segment without stream and scope Name.

### ISSUE THREAD

**Issue by zwx14700** [pravega/pravega#4761]
**Problem description**
I am not sure whether this needs to fix or not, as rawClient is not exposed to User. The problem is found in the rust client integration test (using pravega standalone). If I use a raw client to create a segment(segment-1) directly. It will throw an OOM exception because it doesn't have a dash in the segment name.  

**Problem location**
https://github.com/pravega/pravega/blob/fec616b2d6b0fbf834cc7f59e2d898cdc5ac398f/shared/protocol/src/main/java/io/pravega/shared/NameUtils.java#L312

**Suggestions for an improvement**
It should not throw OOM exception, should give an error message to raw_client.

**Comment by andreipaduroiu** [comment]
Can you please explain how can it throw OOMException? There is nothing in that method that allocates memory.

Do you mean `ArrayIndexOutOfBoundsException`? Reading the next couple of lines, I would be inclined to believe it's this one since, in your case, `tokens` will be a 1-element array and we'll be accessing index 2.

**Comment by zwx14700** [comment]
Sorry for the Wrong explanation, it has been a while since I found this.
