### ISSUE TITLE
System tests are failing in Pravega

### ISSUE THREAD

**Issue by anishakj** [pravega/pravega#5060]
**Problem description**

Pravega system tests are failing in the master branch. Controller scaling is getting timeout. This issue is happening after the upgrade of grpc-netty to 1.31.0.

**Problem location**

**Suggestions for an improvement**

System tests should pass

**Comment by derekm** [comment]
Upgrading grpc-netty to 1.31.0 negatively impacted the k8sClient used by the system tests.

1.31.0 was the most recent version that would allow me to bring pravega-client into more modern Java application frameworks. ... 1.20.0 is the oldest version that allows me to bring pravega-client into newer frameworks. Downgrading to 1.20.0 fixes the system tests while still allowing me to use pravega-client in my projects.

I'll walk up the gRPC version from here and see where the tests brake. Otherwise, I haven't been able to pinpoint what exactly 1.31.0 force-upgrades that breaks the k8sClient.

**Comment by derekm** [comment]
gRPC 1.24.2 was as high as I could upgrade without breaking K8sClient in the systems tests. I'll look to analyze dependency overrides given 1.25.0 vs. 1.24.2 to see if I can pinpoint the issue (in support of any future upgrades).
