### ISSUE TITLE
PDP 46: Read Only Permissions For Reading Data

### ISSUE THREAD

**Issue by ravisharda** [pravega/pravega#5115]
**Problem description**
Discuss [PDP 46: Read Only Permissions For Reading Data](https://github.com/pravega/pravega/wiki/PDP-46:-Read-Only-Permissions-For-Reading-Data)

**Problem location**
See the PDP.

**Suggestions for an improvement**

**Comment by sarlaccpit** [comment]
@ravisharda great write-up.   Here are my comments:

**On section II:**  I follow completely.   The only comment I had there is maybe "target permission" might not be the clearest term.  If I understand the concepts well, it would be the "requested permission".  In other words what the client wants to have in its delegation token to later access the SS in a READ or READ_UPDATE manner.    And there is the "[minimum] required" permission which is the controller's way of saying: you need _at least_ this to access this call.

Did I get that right?   If so, my suggestion would just be:
required permission -->  minimum required permission
target permission --> requested permission

**On section III**:  If "_The solution is to treat these internal streams differently_" , be it watermark or reader group internal streams, instead of letting them be written to by a READ client, couldn't they _really_ be treated differently (basically not as streams, but as the different objects that they are, which would map to the authorization string changes from PDP 42, `prn::/scope:MarketData/reader-group:RG1`  or `prn::/scope:MarketData/watermark:WM1`?    

Then as an admin configuring acls, I can be as granular as dealing with each of these two objects specifically:
`READ_UPDATE` on `prn::/scope:MarketData/watermark:WM1` for `jack`  and 
`READ_UPDATE` on `prn::/scope:MarketData/reader-group:RG1` for `jack` and
`READ` on `prn::/scope:MarketData/stream:stream1` for `jack`

Or as broad as `READ` on `prn:://scope:MarketData/stream:*` for jack and
`READ_UPDATE` on `prn::/scope:MarketData/watermark:WM1` for `jack`  and 
`READ_UPDATE` on `prn::/scope:MarketData/reader-group:RG1` for `jack`

Or also:
`READ` on  `prn:://scope:MarketData/stream:*` for jack and
`READ_UPDATE` on `prn::/scope:MarketData/watermark:*` for `jack`  and 
`READ_UPDATE` on `prn::/scope:MarketData/reader-group:*` for `jack`

And if i'm concerned for jack to be messing with WMs or RGs that don't belong to him but still want to keep things at a high level, I could use a separate scope:

READ `prn:://scope:MarketData/stream:*` for jack and
`READ_UPDATE` on `prn::/scope:scratch/watermark:*` for `jack`  and 
`READ_UPDATE` on `prn::/scope:scratch/reader-group:*` for `jack`

**Comment by fpj** [comment]
@ravi one clarification question about this section:

https://github.com/pravega/pravega/wiki/PDP-46:-Read-Only-Permissions-For-Reading-Data#i-reduce-permissions-required-for-methods-returning-delegation-tokens-to-read

Isn't it the case that writers also invoke `getCurrentSegments` to be able to write? In the case that it is a writer getting the segments, then. how does it obtain a `READ_UPDATE` token?

**Comment by fpj** [comment]
I might be able to answer my own question. I think the answer is in the next section: the writer would have an RP that states that it needs `READ_UPDATE` access.
