### ISSUE TITLE
Consumption Based Retention Improvements

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega#5356]
**Problem description**
Consumption based retention to be implicit based on Reader Groups publishing StreamCuts to controller instead of being explicitly set as a Retention Policy on Controller.

**Problem location**
Controller

**Suggestions for an improvement**
https://github.com/pravega/pravega/pull/5304#discussion_r526449191

**Comment by fpj** [comment]
@pbelgundi @tkaitchuck @shiveshr I wanted us to reach some agreement on a few things:

1- Whether to have `CONSUMPTION` being a explicit retention option or make the behavior available for all streams (enabled and configured via reader group configuration).
2- If we agree that there is a need for a explicit retention option, then is `CONSUMPTION` the best name?
3- The names used in the reader group config as described above. I wonder if they are clear or just confusing the user.

**Comment by tkaitchuck** [comment]
To put a concrete proposal on the table:

I propose that `StreamConfiguration` have a `RetentionPolicy` (as it does now)
and that that policy consist of a `RetentionType` with the options `TIME` and `SIZE` (as it does now)
and that instead of a single member `retentionParam` that exists now, we have a `minRetentionParam` and a `maxRetentionParam`. We will need to keep the getter method `getRetentionParam()` for backward compatibility. (This can return the min).
We currently have two builder methods `byTime` and `bySizeBytes` which each take a single argument. (These need to be maintained for backwards compatibility)
I propose that these methods be overloaded to versions taking two parameters one for the min and one for the max. (The single argument versions just delegate to these passing the same value to in both places)

On the ReaderGroupConfig we need to add a new member variable to contain the setting. I propose this be called "`requestedRetention`" which is an enum with three possible values. 
I propose these be named `NONE`, `UNTIL_CHECKPOINT`, and `UNTIL_UPDATED`. 
Finally there is a new method on the `RederGroup` which can be called `updateRequestedRetention()`

---

Of these names, I most like the StreamConfiguration ones. I am not particularly happy with "UNTIL_UPDATED" or "updateRequestedRetention". The later could be "updateRetentionStreamCut" or some other name, but I would like it to include the noun for the member in the ReaderGroupConfig and the verb from the enum value under which it is active. IE: The "update" is the same as "until_update" and the "requested retention" comes from the field. So if we prefer "updateRetentionStreamCut" then the enum value would be "UNTIL_STREAM_CUT" which seems a bit better for the method name, but worse for the enum value.
