### ISSUE TITLE
Update Copyright section to include "Pravega Authors" 

### ISSUE THREAD

**Issue by medvedevigorek** [pravega/pravega#5697]
**Problem description**
The copyright section of source files should include "Pravega Authors" as the project is moving towards CNCF umbrella 

**Problem location**
HEADER and all source files 

**Suggestions for an improvement**
Either update just a HEADER file or HEADER and all source files to reflect the new change.

**Comment by fpj** [comment]
We need to at least change the `HEADER`  file so that new files from now own add the correct copyright statement. 

@derekm do we need to update the license header in all files or is it only from the point we update the `HEADER` onward?

We need to also change the checkstyle configuration to make sure that new files have the correct statement. (I'm actually not entirely sure whether we can check only new files.)

**Comment by derekm** [comment]
@fpj -- I think the choice is ours whether to update all files at once or not. Can we say we don't maintain the in-place headers, we just add the current header to new files?

**Comment by derekm** [comment]
Fixed by #5807 and #5684
