### ISSUE TITLE
Missing line to wait for Future tasks to be completed

### ISSUE THREAD

**Issue by ManishKumarKeshri** [pravega/pravega#5820]
**Describe the bug**
I was going through the code and found out that a line was missing to wait for future tasks to be completed. 
We should call join or get on the list of futures [here ](https://github.com/pravega/pravega/blob/fa55f21eee4467c9997fe0d6ea877e376139d493/segmentstore/server/src/test/java/io/pravega/segmentstore/server/containers/StreamSegmentContainerTests.java#L483)for the opFutures(list of futures) to be completed. 

**To Reproduce**
It doesn't cause any test to fail or be flaky. 

**Expected behavior**
The test works as it should. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by RaulGracia** [comment]
@ManishKumarKeshri as I understand, this is pointing to an issue on a test, right? However, the description of the issue makes it hard to understand either the context or the manifestation of the problem. Please, make an effort to provide a better description/title as well as the appropriate labels (e.g., "flakyTest" if this is a test that fails sporadically, etc.). Also, if the problem relates to a test has been already reported as problematic, then this issue is redundant, so please look if this is the case.
