### ISSUE TITLE
Change segment store service host address in a Pravega standalone cluster in docker

### ISSUE THREAD

**Issue by fyang86** [pravega/pravega#6204]
# Ask your question away
We are running a Pravega standalone and a schema registry service inside a docker compose environment. When the schema registry tried to communicate with segment store, it always got `localhost` as the service host address. 
Found the config of standalone cluster:
https://github.com/pravega/pravega/blob/39a39871e01eff63f8b87a2858c495673d77ba05/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L302
https://github.com/pravega/pravega/blob/39a39871e01eff63f8b87a2858c495673d77ba05/standalone/src/main/java/io/pravega/local/InProcPravegaCluster.java#L303

Is there any approach to change the segment store host address prior to the Pravega container start?

**Comment by fyang86** [comment]
I tried to set environment variable `HOST_IP` in `docker-compose.yml`, but the endpoint is still LOCALHOST. In `InProcPravegaCluster` it will overwrite the systemproperties with the specific serviceconfig so that the service is always LOCALHOST in standalone cluster.

**Comment by derekm** [comment]
@fyang86 -- see also Issue #6060

**Comment by crazyzhou** [comment]
@derekm -- This issue is different from #6060 . #6060 is a specific issue with the windows and docker network, but this time we run it purely on a ubuntu VM.
The steps to reproduce and the result is quite similar, we start the docker standalone with
```
docker run -it -p 9090:9090 -p 12345:12345 pravega/pravega:latest standalone
```
and use `pravega-cli` (as the issue description mentioned, we first found the problem when we use schema registry together with pravega, but we removed that here to locate the problem and help to clarify) to connect to the controller,
with the official `0.9.1` image, both the scope/stream creation and data writing/reading are fine
with the self built image on latest 0.10-snapshot master branch, the scope/stream creation is fine, but data writing hangs with connection time out.

The root cause for this issue is different. It is because after #4999 , the segment store IP for pravega standalone is no longer an empty string, but a hardcoded `localhost`. This would not influence the normal standalone setups on machine directly, so the tests and CI can pass, but it would break in segment store connection on the docker network.

cc. the PR author @tkaitchuck We have the document [here](https://github.com/pravega/pravega/blob/master/documentation/src/docs/deployment/run-local.md#from-docker-image) teaching users to use standalone in docker, but it does not work now.
