### ISSUE TITLE
Data corruption with batch transaction merge.

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega#6614]
(This affects master and is not believed to affect any released version)

**Describe the bug**
In some cases when a batch transaction commit is invoked the resulting data is corrupted in the following way:
A transaction batch commit is performed with multiple transactions with the same merge target. Each containing multiple (25) events of fixed size. 
When the data is read back the first transaction of the batch is fine however after this there are ~200 bytes of zeros followed by what is presumably data from other transactions but as it does not begin with an event header this is unreadable via the event or batch APIs. Meaning that once this occurs the segment is permanently corrupted and no data after that point can be read.

The number of zeros does not align to event size or to a transaction size. 

**To Reproduce**
Discovered in the system test: `ReadTxnWriteScaleWithFailoverTest`.
A modified version of this test to produce more debugging information is here: https://github.com/pravega/pravega/compare/master...SrishT:systest-txn-failover?expand=1

**Speculation**
This almost certainly is triggered by transaction merge batching as the test never failed prior to its introduction, and the problem cannot be reproduced without it. The other attributes of this test which seem necessary to reproduce the problem (Multiple writers, Failover, and Scaling) all serve to make batching of transaction commits more likely to occur. Given the nature of the problem it is unlikely that any behavior of the client or the controller could be the root cause.

The most likely culprit is related to the specialized handling of segment merges of in memory data in the segment store, specifically in the streaming cache. The presence of zeros indicates it is possible that one chunk of the data being copied is being pulled from the wrong location. This could be triggered by batch merges because they are executed as independent calls to the segment store all at once, so perhaps there is a portion of the code which is not properly serialized or synchronized.

**Comment by andreipaduroiu** [comment]
As a way to improve resiliency, would it be possible to have the Reader interpret the zeroes as "an event with zero length"? Which means, I read 8 bytes evaluated to "0", so I will read the next "0" bytes to load the event. Since there is nothing to read, the Reader could skip this and move over to the next event. While this doesn't solve the underlying segment corruption, it can at least unblock the reader. There should also be a mechanism to report these types of events so they don't go by unnoticed. 

Of course this would only work if the number of zeroed out bytes is a multiple of 8 (event header).
