### ISSUE TITLE
Replace Bookkeeper with Local File System

### ISSUE THREAD

**Issue by jsntmaoxx** [pravega/pravega#6698]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A new class FileSystemLog which implements DurableDataLog interface is used to replace BookKeeperLog to complete all the Durable Log related function. It writes and reads data to and from the local file system, but without replica and fault-tolerant mechanism.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RaulGracia** [comment]
Is this needed for tests? Because we have an `InMemoryDurableDataLog` already in place for that. If not, you could download Bookkeeper and run `bin/bookkeeper standalone` or `bin/bookkeeper localbookie 1` to instantiate a single Bookie locally and work with the existing `BookKeeperLog` implementation.
