### ISSUE TITLE
Shadow segment creation for event stream

### ISSUE THREAD

**Issue by anju-c-das** [pravega/pravega#7149]
**Is your feature request related to a problem? Please describe.**
 Spark attempts to load the whole batch of data into Ram before it processes any of it. This means that if for some reason the readers are slow on one batch and a lot of data is written while it is being processed, and when the workers attempt to load the next batch they will OOM.
 The goal is to create a way to create a streamCut that it in a location that has not yet been read but is a bounded distance from the reader's current location.
To implement the ability to find such a stream cut, we create an index segment. Because this will apply to all event streams, it will be managed server side.

**Describe the solution you'd like**
- creates a new shadow segment for event streams. Initialize an "event number" attribute on the segment that can be checked and updated at append time.
- Binds the lifecycle of the shadow segment with parent segment.
- Enforce that appends to this segment are fixed size records.
- If the main segment is deleted, then shadow segment associated with it is also deleted.

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by RaulGracia** [comment]
@anju-c-das it would be great to give more context on the context, problem, and expected solution for this issue. The current description does not provide enough detail of either the problem that it describes (i.e., what is the `spark reader failure with java heap OOM issue`?), the root cause of the problem (do you know why the problem happens? it is specific for a single type or reader (spark)?), and the extent of the proposed change (is the proposed solution suggesting created a new `shadow` segment for every stream to address a problem with a specific reader?). Please, more details on this would make it easier for others to help with this issue.

cc/ @tkaitchuck @sachin-j-joshi @abhinb

**Comment by anju-c-das** [comment]
Thanks @RaulGracia , I have updated the description.

**Comment by tkaitchuck** [comment]
For more context see PDP-55:
https://github.com/pravega/pravega/wiki/PDP-55:-New-reader-API-on-segment-level

**Comment by Bhupender-Y** [comment]
Completed with #7144
