### ISSUE TITLE
Pravega components should not commit suicide if dependencies aren't available

### ISSUE THREAD

**Issue by fpj** [pravega/pravega#741]
**Problem description**
Controller and host have dependencies like ZooKeeper and BookKeeper. Currently, these components break if the dependencies aren't available while we should really have them wait until the dependency is up so that we can start services in parallel.

**Problem location**
Controller and Segment Store.

**Suggestions for an improvement**
Wait until dependencies are up rather than exiting.

**Comment by fpj** [comment]
@shiveshr @andreipaduroiu What currently happens in the case ZK, BK or both are still coming up? Do the controller and segment store wait?

**Comment by andreipaduroiu** [comment]
In the Segment Store, ZK is only used in ZKSegmentContainerMonitor and Bookkeeper Client. The BK client will stop functioning if ZK is unavailable, causing segment container to shut down to prevent state corruption. They will continuously try to restart until the problem is solved.

I think ZKSegmentContainerMonitor won't stop any containers that are already running if it loses ZK connection (which can lead to a zombie container situation), but I think that after a prolonged failure, it may end up stopping completely.
