### ISSUE TITLE
Latency metrics aren't being set to zero

### ISSUE THREAD

**Issue by glounder** [pravega/pravega#896]
**Problem description**
New latency metrics aren't being set to zero when there is no traffic.  Since the value is a gauge, last value is remembered.  

host.segment_read_latency_ms
host.segment_write_latency_ms

![screen shot 2017-03-29 at 4 30 46 pm](https://cloud.githubusercontent.com/assets/9335655/24472721/1c89af92-149d-11e7-8f5b-a50024cc78fa.png)

**Problem location**
Metrics

**Suggestions for an improvement**
The value needs to be reset to zero when there is no latency.

**Comment by fpj** [comment]
It is not clear to me how to reset the latency to zero unless the metrics lib does it for us. The latency is updated reactively, upon a call to `readSegment`:

```
@Override
    public void readSegment(ReadSegment readSegment) {
        Timer timer = new Timer();
        final String segment = readSegment.getSegment();
        final int readSize = min(MAX_READ_SIZE, max(TYPE_PLUS_LENGTH_SIZE, readSegment.getSuggestedLength()));

        CompletableFuture<ReadResult> future = segmentStore.read(segment, readSegment.getOffset(), readSize, TIMEOUT);
        future.thenApply((ReadResult t) -> {
            handleReadResult(readSegment, t);
            DYNAMIC_LOGGER.incCounterValue(nameFromSegment(SEGMENT_READ_BYTES, segment), t.getConsumedLength());
            READ_STREAM_SEGMENT.reportSuccessEvent(timer.getElapsed());
            return null;
        }).exceptionally((Throwable t) -> {
            handleException(readSegment.getOffset(), segment, "Read segment", t);
            return null;
        });
    }
```

In the absence of a call, we can't reset anything, unless we spawn a thread to do it (or a task in some form), and I'd rather not have to do it. Does anyone have a suggestion here?

**Comment by bayarsaikhan** [comment]
@glounder we haven't resolved this issue right? or at least found solution on the consumer end. please confirm

**Comment by glounder** [comment]
I started thinking about this when Flavio responded to the issue.  This was a problem in graphite because it always remembered the last entry.  Since we are storing the metrics in influx, we may have another option.  I think if we run the query to calculate the average latency, we can shorten the window of data we look at.  If we do this, I think the value will be reported as zero.  I've created an issue to confirm that this will work for us.

This would still be an issue for people storing their data in graphite though.

**Comment by Abhijeet-Jadhav** [comment]
Thanks @glounder. Let us know if it works for influx.

**Comment by askewj** [comment]
@glounder Can this issue be resolved?

**Comment by glounder** [comment]
I played around with this, but I couldn't get it the work.  Here is what I think is going on:

- In the UI, we are currently showing the 95th percentile of the latency.
- The 95th percentile is being calculated in pravega and stored in memory.
- Because the zeros aren't being sent, once the traffic stops, the value stored in memory in pravega never changes (because no new values are showing up).
- That value in memory is being sent as a metric every 10 seconds as a gauge to influx.
- Since the value stored in memory is being sent every 10 seconds, influx thinks its getting an updated value all the time, so we still get an entry for every 10 second interval.

I believe the problem on the Pravega side is that they only record the latency metric when there is data flowing through the system.  Its hard to record the zeros when nothing is going on.

Once solution is to write an adapter that bypasses the drop wizard metrics and sends the raw metrics to some endpoint (statsd and/or influx).  That way, Pravega doesn't use any resources to calculate and store the metrics in memory, they just fire off the metrics and that's it.  On our side, we'd only get latency values when there is traffic and nothing if there is nothing going on.  From that, we can calculate the 95th percentile ourself and fill the missing values with zeros to get the correct numbers.

**Comment by askewj** [comment]
I checked with PM on SRM team since metrics are their daily job.  Based on following, I'd recommend we show Not Available if we don't have a fresh enough value to display.  However I don't think this is a priority to resolve currently.    

There appears to be no consensus on behavior of latency in absence of traffic, it's up to implementer / product.   
-	Currently in SRM, they look at the last 2 weeks of data and take the last known value from this range.  This has been requested by the field (and some customers) so we don’t present blank reports (or blank cells in tables). 
-	SRM PM is not a big fan of this and prefers to show “NA – Not Available” when the data is not “fresh enough” for performance metrics.  Specifically for latency it could be equal to 0 if it is shown along along with the traffic information which also shows 0, in that case the user will see there’s no traffic and understand the latency value of 0.

**Comment by chrisdail** [comment]
@askewj The issue is not that we have a period where we are not getting the data. The issue is we always get the data even if it is out of date. The stale values in memory of the old latency are sent across the wire when no data is read/written. We cannot fix this downstream because we have no way to know if the values it is sending us are real ones (the latency is actually that value) or if they are fake caused by stale data.

**Comment by arvindkandhare** [comment]
@chrisdail  @glounder Is it enough from Pravega side to not send any values if there are no updates since the last report for individual counter/gauge? If yes, I can try and see if this can be achieved. I think this will also help with #1828.

**Comment by glounder** [comment]
I don't think this would work for the latency.  Pravega is currently reporting this as a histogram, so not sending the values is not what we want.  Zero values need to be pumped into the histogram so the calculated values over time changes.  We need to be able to see the 95 percentile slowly go down over time when nothing is happening.

If we were able to get some sort of raw metrics for the latency, not sending the value might work.  We'd need to calculate the histograms values on our end to do this as well.

For #1828, no longer sending total count of bytes read or writes would probably work.  We'd need to make changes in our code to make sure this works.
