### ISSUE TITLE
List Streams REST JSON truncated with large number of streams

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega#926]
**Problem description**
With 300+ streams the listStreams REST call does not return a full JSON payload

**Problem location**
curl http://controller.pravega.marathon.mesos:10080/v1/scopes/dave/streams

Gives a JSON response that ends after 63,913 bytes with:

```{"scopeName":"dave","streamName":"ReaderGroupf477d9126bb34ef382998b713397e381","scalingPolicy":{"type":"FIXED_NUM_SEGMENTS","targetRate":0,"scaleFactor":0,"minSegments":1},"retentionPolicy":{"type":"INFINITE"}},{"scopeName":"dave","```

**Suggestions for an improvement**

Return full JSON payload as this currently breaks the Streams view on the UI

**Comment by skrishnappa** [comment]
Re-opening this since the 200 limit is just a workaround. The main issue of REST API not returning large response body is still not fixed.

**Comment by skrishnappa** [comment]
The truncation issue is due to Jersey's Netty Connector and is reported here (https://github.com/jersey/jersey/issues/3500).
The issue is observed when the server unsent buffer is greater than 8*8000 bytes.
Currently there is no fix proposed for this and suggestion is to use jersey-container-grizzly2-http instead of the netty container.
